import { useEffect, useMemo, useState } from "react";

type Workspace={id:string;label:string;description:string;root:string;workflowDirectoryRelative:string;taskDirectoryRelative:string;backendDirectoryRelative?:string;workflowFileCount:number;taskFileCount:number;backendFileCount?:number};
type Step={id:string;kind?:string;implementation?:string;operation?:string;dependsOn?:string[];inputs?:Record<string,unknown>;outputs?:Record<string,string>;parameters?:Record<string,unknown>;form?:Record<string,unknown>};
type Workflow={id:string;version?:number;label?:string;description?:string;inputs?:Record<string,string>;outputs?:Record<string,string>;steps:Step[]};
type RecordFile<T>={path:string;source?:"shared"|"workspace";workspaceId?:string;document?:T;error?:string};
type TaskDef={id:string;kind?:string;label?:string;description?:string;implementation:string;inputs?:Record<string,string>;outputs?:Record<string,string>;parameters?:Record<string,unknown>};
type BackendDef={kind:"backend";id:string;label?:string;description?:string;provider:string;enabled?:boolean;capabilities?:string[];executable?:string;endpoint?:string;model?:string;env?:Record<string,string>;settings?:Record<string,unknown>};
type WorkspaceFile={path:string;name:string;suffix:string;size:number;modified:number;kind:string};
type Snapshot={workspace:Workspace;workflows:RecordFile<Workflow>[];tasks:RecordFile<TaskDef>[];backends:RecordFile<BackendDef>[];files:WorkspaceFile[]};
type Run={id:string;workflowId:string;workflowVersion:number;status:string;inputs:any;outputs:any;error?:string;steps:any[];artifacts:any[];events:any[];logs:any[];children:any[]};
type Capability={status:string;detail:string};
type View="canvas"|"editor"|"artifacts"|"evidence"|"tasks"|"llms"|"checks"|"setup";
type GraphMode="topology"|"chronology";

async function request(path:string,init?:RequestInit){const r=await fetch(path,{headers:{"Content-Type":"application/json",...(init?.headers||{})},...init});const p=await r.json();if(!r.ok)throw new Error(p.error||p.detail||r.statusText);return p;}
const engine=(path:string,init?:RequestInit)=>request(`/api/engine${path}`,init);
const slug=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"")||"item";
const deps=(step:Step,steps:Step[])=>{const inferred=Object.values(step.inputs||{}).flatMap(v=>{if(typeof v!=="string"||!v.startsWith("$"))return[];const n=v.split(".").pop();return steps.filter(c=>Object.values(c.outputs||{}).includes(String(n))).map(c=>c.id)});return [...new Set([...(step.dependsOn||[]),...inferred])];};

function Topology({workflow,run,selected,onSelect}:{workflow:Workflow;run:Run|null;selected:string|null;onSelect:(id:string)=>void}){const width=Math.max(900,workflow.steps.length*185);const pos=new Map(workflow.steps.map((s,i)=>[s.id,{x:105+i*175,y:90+(i%2)*125}]));return <div className="graph-scroll"><svg className="workflow-graph" viewBox={`0 0 ${width} 340`} style={{minWidth:width}}><defs><marker id="arrow-live" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto"><path d="M0 0L10 5L0 10z"/></marker></defs>{workflow.steps.flatMap(s=>deps(s,workflow.steps).map(d=>{const a=pos.get(d),b=pos.get(s.id);if(!a||!b)return null;const mid=(a.x+b.x)/2;return <path key={`${d}-${s.id}`} className="graph-edge" d={`M${a.x+60},${a.y} C${mid},${a.y} ${mid},${b.y} ${b.x-60},${b.y}`} markerEnd="url(#arrow-live)"/>}))}{workflow.steps.map(s=>{const p=pos.get(s.id)!;const status=run?.steps.find(x=>x.stepId===s.id)?.status||"defined";return <g key={s.id} transform={`translate(${p.x-65},${p.y-40})`} className={`graph-node ${status} ${selected===s.id?"selected":""}`} onClick={()=>onSelect(s.id)}><rect width="130" height="80" rx="11"/><text x="65" y="24" textAnchor="middle" className="node-title">{s.id}</text><text x="65" y="46" textAnchor="middle">{s.implementation||s.kind||"task"}</text><text x="65" y="66" textAnchor="middle" className="node-status">{status}</text></g>})}</svg></div>}
function Chronology({run,onSelect}:{run:Run|null;onSelect:(id:string)=>void}){if(!run)return <div className="empty-state">Run the workflow to create the persisted chronology.</div>;return <div className="chronology-track">{run.events.map((e,i)=><button key={e.id} className="chrono-event" onClick={()=>e.stepId&&onSelect(e.stepId)}><span>{i+1}</span><b>{e.kind}</b><small>{e.stepId||"workflow"}</small><time>{e.createdAt}</time></button>)}</div>}

export function WorkspaceBackedWorkbenchPage(){
 const[workspaces,setWorkspaces]=useState<Workspace[]>([]),[workspace,setWorkspace]=useState<Workspace|null>(null),[snapshot,setSnapshot]=useState<Snapshot|null>(null);
 const[view,setView]=useState<View>("canvas"),[mode,setMode]=useState<GraphMode>("topology"),[workflowPath,setWorkflowPath]=useState(""),[source,setSource]=useState(""),[inputs,setInputs]=useState("{}"),[selectedStep,setSelectedStep]=useState<string|null>(null),[run,setRun]=useState<Run|null>(null);
 const[task,setTask]=useState<RecordFile<TaskDef>|null>(null),[taskSource,setTaskSource]=useState(""),[taskTarget,setTaskTarget]=useState<string|null>(null),[backend,setBackend]=useState<RecordFile<BackendDef>|null>(null),[backendSource,setBackendSource]=useState(""),[backendTarget,setBackendTarget]=useState<string|null>(null);
 const[capabilities,setCapabilities]=useState<Record<string,Capability>>({}),[implementations,setImplementations]=useState<any[]>([]),[validation,setValidation]=useState<string[]|null>(null),[humanValues,setHumanValues]=useState("{}"),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);
 const workflow=useMemo<Workflow|null>(()=>{try{return source?JSON.parse(source):null}catch{return null}},[source]);const step=workflow?.steps.find(s=>s.id===selectedStep)||null;const runtime=run?.steps.find(s=>s.stepId===selectedStep)||null;
 useEffect(()=>{void request('/api/workspaces').then(p=>setWorkspaces((p.workspaces||[]).filter((w:Workspace)=>w.id!=="shared"))).catch(e=>setError(String(e)))},[]);
 useEffect(()=>{if(!run||["completed","failed","cancelled"].includes(run.status))return;const t=setInterval(()=>void engine(`/runs/${run.id}`).then(p=>setRun(p.run)).catch(e=>setError(String(e))),1000);return()=>clearInterval(t)},[run?.id,run?.status]);
 const perform=async(fn:()=>Promise<void>)=>{setBusy(true);setError(null);try{await fn()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 const refresh=async()=>{if(!workspace)return null;const p=await request(`/api/workspaces/${encodeURIComponent(workspace.id)}/snapshot`);setSnapshot(p);return p as Snapshot};
 const loadWorkspace=(w:Workspace)=>perform(async()=>{const[s,i,c]=await Promise.all([request(`/api/workspaces/${encodeURIComponent(w.id)}/snapshot`),engine('/implementations'),engine('/capabilities')]);setWorkspace(s.workspace);setSnapshot(s);setImplementations(i.implementations||[]);setCapabilities(c.capabilities||{});const wf=(s.workflows||[]).find((x:RecordFile<Workflow>)=>x.document);if(wf?.document){setWorkflowPath(wf.path);setSource(JSON.stringify(wf.document,null,2));setSelectedStep(wf.document.steps?.[0]?.id||null)}const td=(s.tasks||[])[0]||null;setTask(td);setTaskSource(td?.document?JSON.stringify(td.document,null,2):"");setTaskTarget(td?.source==="workspace"?td.path:null);const bd=(s.backends||[])[0]||null;setBackend(bd);setBackendSource(bd?.document?JSON.stringify(bd.document,null,2):"");setBackendTarget(bd?.source==="workspace"?bd.path:null);setView("canvas");setRun(null)});
 const openWorkflow=(path:string)=>perform(async()=>{if(!workspace)return;const p=await request(`/api/workspaces/${workspace.id}/file?path=${encodeURIComponent(path)}`);setWorkflowPath(path);setSource(p.file.content);try{const d=JSON.parse(p.file.content);setSelectedStep(d.steps?.[0]?.id||null)}catch{setSelectedStep(null)}});
 const saveWorkflow=()=>perform(async()=>{if(!workspace||!workflow)throw new Error("Select a valid workflow");const path=workflowPath||`workflows/${slug(workflow.id)}.json`;await request(`/api/workspaces/${workspace.id}/file`,{method:"PUT",body:JSON.stringify({path,content:JSON.stringify(workflow,null,2)})});setWorkflowPath(path);await refresh()});
 const validate=()=>perform(async()=>{if(!workflow)throw new Error("Invalid workflow JSON");const p=await engine('/workflows/validate',{method:'POST',body:JSON.stringify(workflow)});setValidation(p.errors||[])});
 const runWorkflow=()=>perform(async()=>{if(!workflow)throw new Error("Invalid workflow JSON");let saved=workflow;if(!saved.version){const p=await engine('/workflows',{method:'POST',body:JSON.stringify(saved)});saved=p.workflow;setSource(JSON.stringify(saved,null,2));await request(`/api/workspaces/${workspace!.id}/file`,{method:'PUT',body:JSON.stringify({path:workflowPath||`workflows/${slug(saved.id)}.json`,content:JSON.stringify(saved,null,2)})})}const p=await engine('/runs',{method:'POST',body:JSON.stringify({workflowId:saved.id,version:saved.version,inputs:JSON.parse(inputs)})});setRun(p.run);setMode("chronology")});
 const command=(name:string)=>perform(async()=>{if(!run)return;const p=await engine(`/runs/${run.id}/commands`,{method:'POST',body:JSON.stringify({command:name})});setRun(p.run)});
 const submitHuman=()=>perform(async()=>{if(!run||!selectedStep)return;const p=await engine(`/runs/${run.id}/steps/${selectedStep}/input`,{method:'POST',body:humanValues});setRun(p.run)});
 const copyTask=()=>{if(!workspace||!task?.document)return;const id=task.document.id.replace(/^shared\./,'');const d={...task.document,id:`${workspace.id}.${id}`};setTaskSource(JSON.stringify(d,null,2));setTaskTarget(`tasks/${slug(id)}.json`)};
 const saveTask=()=>perform(async()=>{if(!workspace)throw new Error("Select workspace");const d=JSON.parse(taskSource);const path=taskTarget||`tasks/${slug(d.id)}.json`;await request(`/api/workspaces/${workspace.id}/file`,{method:'PUT',body:JSON.stringify({path,content:JSON.stringify(d,null,2)})});await refresh();setTaskTarget(path)});
 const copyBackend=()=>{if(!workspace||!backend?.document)return;const d={...backend.document};setBackendSource(JSON.stringify(d,null,2));setBackendTarget(`backends/${slug(d.id)}.json`)};
 const saveBackend=()=>perform(async()=>{if(!workspace)throw new Error("Select workspace");const d=JSON.parse(backendSource);if(d.kind!=="backend")throw new Error("Backend must declare kind: backend");const path=backendTarget||`backends/${slug(d.id)}.json`;await request(`/api/workspaces/${workspace.id}/file`,{method:'PUT',body:JSON.stringify({path,content:JSON.stringify(d,null,2)})});await refresh();setBackendTarget(path)});

 if(!workspace)return <main className="workbench-shell"><section className="workspace-gate"><div className="brand-lockup"><span className="brand-mark">M</span><div><b>MeTTa Symbolic Learner Workbench</b><small>Choose a filesystem workspace</small></div></div><div className="workspace-picker-grid">{workspaces.map(w=><button className="workspace-card" key={w.root} onClick={()=>loadWorkspace(w)}><h2>{w.label}</h2><p>{w.description}</p><strong>{w.workflowFileCount} workflows · {w.taskFileCount||0} local tasks · {w.backendFileCount||0} local backends</strong><small>{w.root}</small></button>)}</div>{error&&<div className="engine-error">{error}</div>}</section></main>;

 return <main className="workbench-shell"><aside className="left-rail"><div className="brand-lockup"><span className="brand-mark">M</span><div><b>MeTTa Workbench</b><small>{workspace.label}</small></div></div><nav>{([['canvas','Workflow'],['editor','Editor'],['artifacts','Artifacts'],['evidence','Evidence'],['tasks','Tasks'],['llms','Backends'],['checks','Checks'],['setup','Setup']] as [View,string][]).map(([id,label])=><button key={id} className={view===id?'active':''} onClick={()=>setView(id)}>{label}</button>)}</nav><div className="rail-footer"><span className="status-pill ok">FILESYSTEM</span><button onClick={()=>{setWorkspace(null);setSnapshot(null);setRun(null)}}>Switch workspace</button></div></aside><section className="workbench-main"><header className="topbar"><div><span className="eyebrow">WORKSPACE</span><h1>{workspace.label}</h1><small>{workspace.root}</small></div><div className="topbar-actions">{run&&<span className={`status-pill ${run.status}`}>{run.status}</span>}<span className="status-pill ok">BACKEND LIVE</span></div></header>{error&&<div className="engine-error">{error}<button onClick={()=>setError(null)}>×</button></div>}
 {view==='canvas'&&<><section className="workflow-toolbar"><select value={workflowPath} onChange={e=>openWorkflow(e.target.value)}>{snapshot?.workflows.map(w=><option key={w.path} value={w.path}>{w.document?.label||w.document?.id||w.path}</option>)}</select><button className={mode==='topology'?'active':''} onClick={()=>setMode('topology')}>Topology</button><button className={mode==='chronology'?'active':''} onClick={()=>setMode('chronology')}>Chronology</button><button onClick={validate}>Validate</button><button onClick={saveWorkflow}>Save</button><button className="primary" onClick={runWorkflow} disabled={busy}>Run workflow</button></section><section className="workflow-desktop"><aside className="stage-rail"><span className="eyebrow">REAL STEPS</span>{workflow?.steps.map((s,i)=>{const st=run?.steps.find(x=>x.stepId===s.id)?.status||'defined';return <button key={s.id} className={selectedStep===s.id?'active':''} onClick={()=>setSelectedStep(s.id)}><span className="stage-number">{String(i+1).padStart(2,'0')}</span><div><b>{s.id}</b><small>{s.implementation||s.operation||s.kind||'task'}</small></div><em>{st}</em></button>})}</aside><section className="workflow-canvas">{workflow&&(mode==='topology'?<Topology workflow={workflow} run={run} selected={selectedStep} onSelect={setSelectedStep}/>:<Chronology run={run} onSelect={setSelectedStep}/>)}{validation&&<div className={validation.length?'validation bad':'validation good'}>{validation.length?validation.join('\n'):'Validated by backend'}</div>}{run&&<div className="run-command-bar"><b>{run.id.slice(0,8)}</b><button onClick={()=>command('pause')}>Pause</button><button onClick={()=>command('resume')}>Resume</button><button onClick={()=>command('advance')}>Advance</button><button onClick={()=>command('replay')}>Replay</button><button onClick={()=>command('cancel')}>Cancel</button></div>}</section><aside className="inspector-panel"><span className="eyebrow">INSPECTOR</span>{step?<><h2>{step.id}</h2><p>{step.implementation||step.operation||step.kind}</p><dl><dt>Status</dt><dd>{runtime?.status||'defined'}</dd><dt>Attempts</dt><dd>{runtime?.attempt||0}</dd></dl><details open><summary>Inputs</summary><pre>{JSON.stringify(step.inputs||{},null,2)}</pre></details><details><summary>Outputs</summary><pre>{JSON.stringify(step.outputs||{},null,2)}</pre></details>{runtime?.status==='waiting'&&<><textarea value={humanValues} onChange={e=>setHumanValues(e.target.value)}/><button className="primary" onClick={submitHuman}>Submit human input</button></>}</>:<p>Select a step.</p>}</aside></section></>}
 {view==='editor'&&<section className="panel-page"><div className="panel-heading"><div><span className="eyebrow">WORKFLOW SOURCE</span><h2>{workflowPath}</h2></div><button onClick={saveWorkflow}>Save file</button></div><textarea className="source-editor" value={source} onChange={e=>setSource(e.target.value)}/><label>Run inputs</label><textarea className="input-editor" value={inputs} onChange={e=>setInputs(e.target.value)}/></section>}
 {view==='artifacts'&&<section className="panel-page"><div className="panel-heading"><div><span className="eyebrow">ARTIFACT STORE</span><h2>Persisted run artifacts</h2></div></div>{!run?<div className="empty-state">Run a workflow to create artifacts.</div>:<div className="artifact-table">{run.artifacts.map(a=><details key={a.id}><summary><b>{a.name}</b> <span>{a.datatype}</span></summary><pre>{JSON.stringify(a,null,2)}</pre></details>)}</div>}</section>}
 {view==='evidence'&&<section className="panel-page"><span className="eyebrow">PROVENANCE</span><h2>Events and logs</h2>{!run?<div className="empty-state">Run a workflow to create evidence.</div>:<div className="run-columns"><div>{run.events.map(e=><div className="event" key={e.id}><b>{e.kind}</b><small>{e.stepId||'workflow'} · {e.createdAt}</small></div>)}</div><div>{run.logs.map(l=><div className={`log ${l.stream}`} key={l.id}><b>{l.stream}</b><pre>{l.message}</pre></div>)}</div></div>}</section>}
 {view==='tasks'&&<section className="designer-page"><aside className="designer-library"><span className="eyebrow">TASK LIBRARY</span><h3>Workspace</h3>{snapshot?.tasks.filter(t=>t.source==='workspace').map(t=><button key={t.path} onClick={()=>{setTask(t);setTaskSource(JSON.stringify(t.document,null,2));setTaskTarget(t.path)}}>{t.document?.label||t.document?.id}</button>)}<h3>Shared</h3>{snapshot?.tasks.filter(t=>t.source==='shared').map(t=><button key={`${t.workspaceId}:${t.path}`} onClick={()=>{setTask(t);setTaskSource(JSON.stringify(t.document,null,2));setTaskTarget(null)}}>{t.document?.label||t.document?.id}</button>)}</aside><section className="designer-editor"><div className="panel-heading"><h2>{task?.document?.label||'Task'}</h2><div>{task?.source==='shared'&&<button onClick={copyTask}>Make workspace-specific copy</button>}<button onClick={saveTask}>Save task</button></div></div><textarea className="source-editor" value={taskSource} onChange={e=>setTaskSource(e.target.value)}/></section><aside className="designer-inspector"><h3>Runtime implementation</h3><pre>{JSON.stringify(implementations.find(i=>i.name===task?.document?.implementation)||null,null,2)}</pre></aside></section>}
 {view==='llms'&&<section className="designer-page"><aside className="designer-library"><span className="eyebrow">BACKENDS</span><h3>Workspace</h3>{snapshot?.backends?.filter(b=>b.source==='workspace').map(b=><button key={b.path} onClick={()=>{setBackend(b);setBackendSource(JSON.stringify(b.document,null,2));setBackendTarget(b.path)}}>{b.document?.label||b.document?.id}</button>)}<h3>Shared</h3>{snapshot?.backends?.filter(b=>b.source==='shared').map(b=><button key={`${b.workspaceId}:${b.path}`} onClick={()=>{setBackend(b);setBackendSource(JSON.stringify(b.document,null,2));setBackendTarget(null)}}>{b.document?.label||b.document?.id}</button>)}</aside><section className="designer-editor"><div className="panel-heading"><div><span className="eyebrow">BACKEND DESIGNER</span><h2>{backend?.document?.label||backend?.document?.id||'Backend'}</h2></div><div>{backend?.source==='shared'&&<button onClick={copyBackend}>Make workspace-specific copy</button>}<button onClick={saveBackend}>Save backend</button></div></div><textarea className="source-editor" value={backendSource} onChange={e=>setBackendSource(e.target.value)}/></section><aside className="designer-inspector"><h3>Resolved backend</h3><pre>{backendSource}</pre></aside></section>}
 {view==='checks'&&<section className="panel-page"><span className="eyebrow">VALIDATION</span><h2>Checks are computed, not mocked</h2><button onClick={validate}>Run workflow validation</button>{validation===null?<p>Validation has not been run.</p>:validation.length?<pre>{validation.join('\n')}</pre>:<div className="validation good">All backend workflow checks passed.</div>}<h3>Runtime capabilities</h3>{Object.entries(capabilities).map(([n,c])=><div className="capability-row" key={n}><b>{n}</b><span>{c.status}</span><p>{c.detail}</p></div>)}</section>}
 {view==='setup'&&<section className="panel-page"><span className="eyebrow">FILES + RUNTIME</span><h2>Workspace setup</h2><div className="setup-grid"><div><h3>Real workspace files</h3>{snapshot?.files.slice(0,400).map(f=><div className="file-row" key={f.path}><b>{f.name}</b><small>{f.path}</small></div>)}</div><div><h3>Registered engine implementations</h3>{implementations.map(i=><details key={i.name}><summary>{i.name}</summary><pre>{JSON.stringify(i,null,2)}</pre></details>)}</div></div></section>}
 </section></main>;
}
