(
  (kind concrete_datatype)
  (id json)
  (label Json)
  (implements (
    (json_object (
      (borrow ([]
        *
      ))
      (exclude ([]))
    ))
    (object_list (
      (borrow ([]
        *
      ))
      (exclude ([]))
    ))
    (scene_graph (
      (borrow ([]
        *
      ))
      (exclude ([]))
    ))
  ))
  (mimeTypes ([]
    application/json
  ))
  (extensions ([]
    .json
  ))
)
