"""Shared object-memory contracts for PROLOG, GPT, and PYTHON backends.

The package supplements the existing ARC3 debugger. It does not replace
Arc3Runner, ActionTreeStore, GptArcAnalyzer, SWIPrologBridge, or the generated
Prolog artifact contracts.
"""

from .adapters import (
    GridAdapter,
    GridPerceptionBatch,
    ImageAdapter,
    MediaPerceptionBatch,
    PerceptionAdapter,
    SimpleVideoAdapter,
    normalize_grid_structure,
)
from .acceptance import AcceptanceReport, build_acceptance_report, write_acceptance_report
from .capture import SemanticGridCaptureObserver, standard_semantic_grid_observer
from .benchmark import (
    PerceptionBenchmarkResult,
    PerceptionBenchmarkRunner,
    PerceptionFixture,
    ProviderAblationRunner,
    RasterPerturbationGenerator,
)
from .forms import CellLogoForm, FitResult, GenerativeForm
from .environment_fixtures import (
    EnvironmentProgressionFixtures,
    environment_progression_fixtures,
    fixed_camera_physics_fixtures,
    rendered_arcade_fixtures,
    top_down_manipulation_fixtures,
)
from .integration import (
    GAME_OBJECT_LEARNER_SCHEMA_VERSION,
    GameObjectLearnerPayload,
    GameObjectLearnerPlugin,
    GameObjectLearnerResult,
    GameObjectLearnerSchema,
    IntegrationError,
    IntegrationValidator,
    Phase2LearnerPayloadBuilder,
    PipelineGameObjectLearnerPlugin,
    phase2_transformation_learner,
    phase2_transition_analyzer,
    phase2_rule_inducer,
    phase2_rule_executor,
    phase2_rule_ranker,
)
from .learning import (
    GameLearningPipeline,
    LearningStepResult,
    OutcomeChannel,
    PredictionEvaluator,
    PredictionGrade,
    PredictionGradeStatus,
    RuleEvidence,
    RuleExecutor,
    RuleInducer,
    RuleRanker,
    RuleRivalSet,
    TransformationCandidate,
    TransformationLearner,
    TransitionAnalyzer,
    TransitionRecord,
)
from .models import (
    ActionRecommendation,
    ArtifactRef,
    CandidateObject,
    CommittedAtom,
    ConfidenceHistoryRecord,
    EncounterRecord,
    EvidencePolarity,
    EvidenceRecord,
    ExecutionMode,
    IdentityDecision,
    InstanceParameters,
    MatchProposal,
    MergeDecision,
    NormalizedResult,
    Observation,
    ObjectChange,
    PHASE2_SCHEMA_VERSION,
    PredictionRecord,
    PredictionGradeRecord,
    ProvenanceRef,
    RecognitionAccount,
    ResidualCandidate,
    ResidualDisposition,
    SplitDecision,
    TransitionRule,
    TurtleProgramRef,
    deterministic_identifier,
)
from .memory import EncounterLog, ResidualGate, SingleWriter, SymbolicMemory
from .prediction import PredictionLedger, RuleStore
from .providers import (
    ArtifactProvider,
    GptArtifactProvider,
    PrologProvider,
    ProviderCapabilities,
    PythonProvider,
    UnsupportedProviderCapability,
)
from .recognition import (
    ChangeDetector,
    CorrespondenceEvidenceBuilder,
    EncounterChangeSession,
    InstanceMatcher,
    PartialVisibilityCompletion,
    RecognitionSession,
    RegistryCorrespondenceAuthority,
    ResidualAnalyzer,
    TurtleReconstructionEvidenceBuilder,
)
from .replay import ActionTreeSemanticReplay, PrologSemanticBackend, SemanticRecordCodec
from .sprite import AlphaContourProvider, SpriteAdapter
from .transcript import TranscriptComparison, TranscriptScorer
from .store import ArtifactIndex, InMemorySemanticBackend, SemanticStoreBackend, SymbolicStore

__all__ = [
    "ArtifactProvider",
    "ActionRecommendation",
    "AcceptanceReport",
    "AlphaContourProvider",
    "ActionTreeSemanticReplay",
    "ArtifactRef",
    "ArtifactIndex",
    "CandidateObject",
    "ChangeDetector",
    "CellLogoForm",
    "CommittedAtom",
    "ConfidenceHistoryRecord",
    "CorrespondenceEvidenceBuilder",
    "EncounterRecord",
    "EnvironmentProgressionFixtures",
    "EncounterLog",
    "EncounterChangeSession",
    "EvidencePolarity",
    "EvidenceRecord",
    "ExecutionMode",
    "FitResult",
    "GameLearningPipeline",
    "GAME_OBJECT_LEARNER_SCHEMA_VERSION",
    "GameObjectLearnerPayload",
    "GameObjectLearnerPlugin",
    "GameObjectLearnerResult",
    "GameObjectLearnerSchema",
    "GenerativeForm",
    "GptArtifactProvider",
    "GridAdapter",
    "ImageAdapter",
    "MediaPerceptionBatch",
    "GridPerceptionBatch",
    "IntegrationError",
    "IntegrationValidator",
    "IdentityDecision",
    "InstanceParameters",
    "InstanceMatcher",
    "InMemorySemanticBackend",
    "LearningStepResult",
    "MatchProposal",
    "MergeDecision",
    "NormalizedResult",
    "Observation",
    "ObjectChange",
    "OutcomeChannel",
    "PerceptionAdapter",
    "PerceptionBenchmarkResult",
    "PerceptionBenchmarkRunner",
    "PerceptionFixture",
    "ProviderAblationRunner",
    "SimpleVideoAdapter",
    "PartialVisibilityCompletion",
    "Phase2LearnerPayloadBuilder",
    "phase2_transformation_learner",
    "phase2_transition_analyzer",
    "normalize_grid_structure",
    "phase2_rule_inducer",
    "phase2_rule_executor",
    "phase2_rule_ranker",
    "PipelineGameObjectLearnerPlugin",
    "PredictionEvaluator",
    "PredictionGrade",
    "PredictionGradeStatus",
    "PredictionLedger",
    "PredictionRecord",
    "PredictionGradeRecord",
    "PHASE2_SCHEMA_VERSION",
    "ProvenanceRef",
    "PrologProvider",
    "ProviderCapabilities",
    "PrologSemanticBackend",
    "PythonProvider",
    "ResidualCandidate",
    "ResidualAnalyzer",
    "ResidualDisposition",
    "ResidualGate",
    "RecognitionAccount",
    "RecognitionSession",
    "RasterPerturbationGenerator",
    "RegistryCorrespondenceAuthority",
    "RuleEvidence",
    "RuleExecutor",
    "RuleInducer",
    "RuleRanker",
    "RuleRivalSet",
    "RuleStore",
    "SingleWriter",
    "SpriteAdapter",
    "SemanticStoreBackend",
    "SemanticRecordCodec",
    "SemanticGridCaptureObserver",
    "standard_semantic_grid_observer",
    "SplitDecision",
    "SymbolicMemory",
    "SymbolicStore",
    "TransformationCandidate",
    "TransformationLearner",
    "TransitionAnalyzer",
    "TransitionRecord",
    "TransitionRule",
    "TranscriptComparison",
    "TranscriptScorer",
    "UnsupportedProviderCapability",
    "TurtleProgramRef",
    "TurtleReconstructionEvidenceBuilder",
    "deterministic_identifier",
    "build_acceptance_report",
    "environment_progression_fixtures",
    "fixed_camera_physics_fixtures",
    "rendered_arcade_fixtures",
    "top_down_manipulation_fixtures",
    "write_acceptance_report",
]
