"""Shared object-memory contracts for PROLOG, GPT, and PYTHON backends.

The package supplements the existing ARC3 debugger. It does not replace
Arc3Runner, ActionTreeStore, GptArcAnalyzer, SWIPrologBridge, or the generated
Prolog artifact contracts.
"""

from .adapters import GridAdapter, GridPerceptionBatch, PerceptionAdapter
from .capture import SemanticGridCaptureObserver
from .forms import CellLogoForm, FitResult, GenerativeForm
from .integration import (
    GameObjectLearnerPayload,
    GameObjectLearnerPlugin,
    GameObjectLearnerResult,
    GameObjectLearnerSchema,
    IntegrationError,
    IntegrationValidator,
    PipelineGameObjectLearnerPlugin,
)
from .learning import (
    GameLearningPipeline,
    LearningStepResult,
    OutcomeChannel,
    PredictionEvaluator,
    PredictionGrade,
    RuleEvidence,
    RuleExecutor,
    RuleInducer,
    RuleRanker,
    RuleRivalSet,
    TransformationCandidate,
    TransformationLearner,
    TransitionAnalyzer,
    TransitionRecord,
)
from .models import (
    ArtifactRef,
    CandidateObject,
    CommittedAtom,
    ConfidenceHistoryRecord,
    EncounterRecord,
    EvidencePolarity,
    EvidenceRecord,
    ExecutionMode,
    IdentityDecision,
    InstanceParameters,
    MatchProposal,
    MergeDecision,
    NormalizedResult,
    Observation,
    ObjectChange,
    PHASE2_SCHEMA_VERSION,
    PredictionRecord,
    ProvenanceRef,
    RecognitionAccount,
    ResidualCandidate,
    ResidualDisposition,
    SplitDecision,
    TransitionRule,
    TurtleProgramRef,
    deterministic_identifier,
)
from .memory import EncounterLog, ResidualGate, SingleWriter, SymbolicMemory
from .prediction import PredictionLedger, RuleStore
from .providers import ArtifactProvider, GptArtifactProvider, PrologProvider, PythonProvider
from .recognition import (
    ChangeDetector,
    CorrespondenceEvidenceBuilder,
    InstanceMatcher,
    RecognitionSession,
    RegistryCorrespondenceAuthority,
    TurtleReconstructionEvidenceBuilder,
)
from .replay import ActionTreeSemanticReplay, PrologSemanticBackend, SemanticRecordCodec
from .store import ArtifactIndex, InMemorySemanticBackend, SemanticStoreBackend, SymbolicStore

__all__ = [
    "ArtifactProvider",
    "ActionTreeSemanticReplay",
    "ArtifactRef",
    "ArtifactIndex",
    "CandidateObject",
    "ChangeDetector",
    "CellLogoForm",
    "CommittedAtom",
    "ConfidenceHistoryRecord",
    "CorrespondenceEvidenceBuilder",
    "EncounterRecord",
    "EncounterLog",
    "EvidencePolarity",
    "EvidenceRecord",
    "ExecutionMode",
    "FitResult",
    "GameLearningPipeline",
    "GameObjectLearnerPayload",
    "GameObjectLearnerPlugin",
    "GameObjectLearnerResult",
    "GameObjectLearnerSchema",
    "GenerativeForm",
    "GptArtifactProvider",
    "GridAdapter",
    "GridPerceptionBatch",
    "IntegrationError",
    "IntegrationValidator",
    "IdentityDecision",
    "InstanceParameters",
    "InstanceMatcher",
    "InMemorySemanticBackend",
    "LearningStepResult",
    "MatchProposal",
    "MergeDecision",
    "NormalizedResult",
    "Observation",
    "ObjectChange",
    "OutcomeChannel",
    "PerceptionAdapter",
    "PipelineGameObjectLearnerPlugin",
    "PredictionEvaluator",
    "PredictionGrade",
    "PredictionLedger",
    "PredictionRecord",
    "PHASE2_SCHEMA_VERSION",
    "ProvenanceRef",
    "PrologProvider",
    "PrologSemanticBackend",
    "PythonProvider",
    "ResidualCandidate",
    "ResidualDisposition",
    "ResidualGate",
    "RecognitionAccount",
    "RecognitionSession",
    "RegistryCorrespondenceAuthority",
    "RuleEvidence",
    "RuleExecutor",
    "RuleInducer",
    "RuleRanker",
    "RuleRivalSet",
    "RuleStore",
    "SingleWriter",
    "SemanticStoreBackend",
    "SemanticRecordCodec",
    "SemanticGridCaptureObserver",
    "SplitDecision",
    "SymbolicMemory",
    "SymbolicStore",
    "TransformationCandidate",
    "TransformationLearner",
    "TransitionAnalyzer",
    "TransitionRecord",
    "TransitionRule",
    "TurtleProgramRef",
    "TurtleReconstructionEvidenceBuilder",
    "deterministic_identifier",
]
