(
  (kind representation_datatype)
  (id image_region)
  (label "Image Region")
  (description "A bounded visual subregion associated with an entity or candidate object.")
  (implements (
    (image ())
    (entity ())
  ))
  (implementedBy ())
  (inheritedBy ())
  (inheritsFrom (
    (image (
      (borrow ([]
        *
      ))
      (exclude ([]))
    ))
    (entity (
      (borrow ([]
        *
      ))
      (exclude ([]))
    ))
  ))
)
