(
  (kind representation_datatype)
  (id json_object)
  (label "JSON Object")
  (implements (
    (information (
      (borrow ([]
        *
      ))
      (exclude ([]))
    ))
    (object (
      (borrow ([]
        *
      ))
      (exclude ([]))
    ))
  ))
  (specializations (
    (json (
      (lend ([]
        *
      ))
      (withhold ([]
        id
        label
        description
        implements
        specializations
        preferredSpecialization
      ))
    ))
  ))
  (preferredSpecialization json)
)
