(
  (kind representation_datatype)
  (id json_object)
  (label "JSON Object")
  (implements (
    (information ())
    (object ())
  ))
  (implementedBy (
    (json ())
  ))
  (inheritedBy (
    (json (
      (lend ([]
        *
      ))
      (withhold ([]
        id
        label
        description
        implements
        implementedBy
        preferredImplementation
      ))
    ))
  ))
  (preferredImplementation json)
  (inheritsFrom (
    (information (
      (borrow ([]
        *
      ))
      (exclude ([]))
    ))
    (object (
      (borrow ([]
        *
      ))
      (exclude ([]))
    ))
  ))
)
