(
  (kind representation_datatype)
  (id object_properties)
  (label "Object Properties")
  (description "Structured symbolic properties and relationships describing objects independently of the underlying implementation language.")
  (implements (
    (entity (
      (borrow ([]
        *
      ))
      (exclude ([]))
    ))
    (entity_collection (
      (borrow ([]
        *
      ))
      (exclude ([]))
    ))
    (world_state (
      (borrow ([]
        *
      ))
      (exclude ([]))
    ))
  ))
  (specializations ())
)
