(
  (kind representation_datatype)
  (id python_object)
  (label "Python Object")
  (language python)
  (description "An in-memory Python object representation used by Python operation implementations.")
  (implements (
    (information ())
    (object ())
  ))
  (implementedBy ())
  (inheritedBy ())
  (inheritsFrom (
    (information (
      (borrow ([]
        *
      ))
      (exclude ([]))
    ))
    (object (
      (borrow ([]
        *
      ))
      (exclude ([]))
    ))
  ))
)
