(
  (kind representation_datatype)
  (id scene_graph)
  (label "Scene Graph")
  (implements (
    (image ())
  ))
  (implementedBy (
    (json ())
  ))
  (inheritedBy (
    (json (
      (lend ([]
        *
      ))
      (withhold ([]
        id
        label
        description
        implements
        implementedBy
        preferredImplementation
      ))
    ))
  ))
  (preferredImplementation json)
  (inheritsFrom (
    (image (
      (borrow ([]
        *
      ))
      (exclude ([]))
    ))
  ))
)
