(
  (kind representation_datatype)
  (id svg)
  (label SVG)
  (language image/svg+xml)
  (implements (
    (image ())
  ))
  (implementedBy (
    (svg_xml ())
  ))
  (inheritedBy (
    (svg_xml (
      (lend ([]
        *
      ))
      (withhold ([]
        id
        label
        description
        implements
        implementedBy
        preferredImplementation
      ))
    ))
  ))
  (preferredImplementation svg_xml)
  (inheritsFrom (
    (image (
      (borrow ([]
        *
      ))
      (exclude ([]))
    ))
  ))
)
