import {useEffect,useMemo,useState} from "react";
import {HierarchyResourceEditor} from "./HierarchyResourceEditor";
import {ArtifactTreeBranch} from "./ArtifactTreeBranch";
import {relationshipIds} from "./resourceRelationships";
import {ResourceSourceEditor} from "./ResourceSourceEditor";
import {ResourceEnablementBadge,enablementClass,resolveResourceEnablement,type ResourceEnablement} from "./resourceEnablement";
import "../styles/operation_editor.css";

type RecordFile<T>={path:string;source?:"shared"|"workspace";workspaceId?:string;document?:T;error?:string};
type DatatypeDef={kind:"semantic_datatype";id:string;label?:string;description?:string;enabled?:boolean;extends?:string[];children?:string[];preferredChild?:string;[key:string]:unknown};
type RepresentationDef={kind:"representation_datatype";id:string;label?:string;description?:string;enabled?:boolean;parents:string[];children?:string[];preferredChild?:string;[key:string]:unknown};
type ConcreteDef={kind:"concrete_datatype";id:string;label?:string;description?:string;enabled?:boolean;parents:string[];mimeTypes?:string[];extensions?:string[];[key:string]:unknown};
type DataResource=DatatypeDef|RepresentationDef|ConcreteDef;
type ConversionEdge={operationId:string;label?:string;datatype:string;from:string;to:string;cost:number;lossy?:boolean;expectedAccuracy?:number};
type InventoryRef={ownerKind:string;ownerId:string;direction:string;port:string;datatype:string;representation?:string|null};
type OpenDocument={key:string;record:RecordFile<DataResource>;source:string;dirty:boolean};

async function jsonRequest(path:string,init?:RequestInit){const response=await fetch(path,{headers:{"Content-Type":"application/json",...(init?.headers||{})},...init});const payload=await response.json();if(!response.ok)throw new Error(String(payload.error||payload.detail||response.statusText));return payload;}
const slug=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"")||"item";
const recordKey=(record:RecordFile<DataResource>)=>`${record.workspaceId||record.source||"resource"}:${record.path}:${record.document?.id||"unknown"}`;
const hasParent=(representation:RepresentationDef,datatypeId:string)=>relationshipIds(representation.parents).includes(datatypeId);

export function DataCatalogPanel({workspaceId}:{workspaceId:string}){
 const[datatypes,setDatatypes]=useState<RecordFile<DatatypeDef>[]>([]),[representations,setRepresentations]=useState<RecordFile<RepresentationDef>[]>([]),[concreteDatatypes,setConcreteDatatypes]=useState<RecordFile<ConcreteDef>[]>([]),[edges,setEdges]=useState<ConversionEdge[]>([]),[references,setReferences]=useState<InventoryRef[]>([]),[undeclaredDatatypes,setUndeclaredDatatypes]=useState<string[]>([]),[undeclaredRepresentations,setUndeclaredRepresentations]=useState<string[]>([]),[openDocs,setOpenDocs]=useState<OpenDocument[]>([]),[activeKey,setActiveKey]=useState<string|null>(null),[compareKey,setCompareKey]=useState<string|null>(null),[tab,setTab]=useState<"types"|"conversions"|"usage">("types"),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);
 const refresh=async()=>{const[graph,inventory]=await Promise.all([jsonRequest(`/api/workspaces/${encodeURIComponent(workspaceId)}/representation-graph`),jsonRequest(`/api/workspaces/${encodeURIComponent(workspaceId)}/data-inventory`)]);setDatatypes(graph.datatypes||[]);setRepresentations(graph.representations||[]);setConcreteDatatypes(graph.concreteDatatypes||[]);setEdges(graph.conversionEdges||[]);setReferences(inventory.references||[]);setUndeclaredDatatypes(inventory.undeclaredDatatypes||[]);setUndeclaredRepresentations(inventory.undeclaredRepresentations||[])};
 useEffect(()=>{setOpenDocs([]);setActiveKey(null);setCompareKey(null);setTab("types");void refresh().catch(reason=>setError(String(reason)))},[workspaceId]);
 const byDatatype=useMemo(()=>{const result=new Map<string,RecordFile<RepresentationDef>[]>();for(const datatype of datatypes)result.set(datatype.document?.id||datatype.path,[]);for(const representation of representations){if(!representation.document)continue;for(const datatype of datatypes){const id=datatype.document?.id;if(id&&hasParent(representation.document,id))result.get(id)?.push(representation)}}for(const rows of result.values())rows.sort((a,b)=>String(a.document?.label||a.document?.id||a.path).localeCompare(String(b.document?.label||b.document?.id||b.path)));return result},[datatypes,representations]);
 const byRepresentation=useMemo(()=>{const result=new Map<string,RecordFile<ConcreteDef>[]>();for(const representation of representations)result.set(representation.document?.id||representation.path,[]);for(const concrete of concreteDatatypes){if(!concrete.document)continue;for(const parent of relationshipIds(concrete.document.parents))result.get(parent)?.push(concrete)}return result},[representations,concreteDatatypes]);
 const featuredDatatypes=useMemo(()=>[...datatypes].sort((a,b)=>{const aid=a.document?.id||"",bid=b.document?.id||"",ac=(byDatatype.get(aid)||[]).length,bc=(byDatatype.get(bid)||[]).length;if(aid==="image"&&bid!=="image")return-1;if(bid==="image"&&aid!=="image")return 1;if(bc!==ac)return bc-ac;return String(a.document?.label||aid||a.path).localeCompare(String(b.document?.label||bid||b.path))}),[datatypes,byDatatype]);
 const open=(record:RecordFile<DataResource>)=>{const key=recordKey(record);setOpenDocs(current=>current.some(doc=>doc.key===key)?current:[...current,{key,record,source:record.document?JSON.stringify(record.document,null,2):"",dirty:false}]);setActiveKey(key)};
 useEffect(()=>{if(openDocs.length===0&&featuredDatatypes[0])open(featuredDatatypes[0] as RecordFile<DataResource>)},[featuredDatatypes]);
 const active=openDocs.find(doc=>doc.key===activeKey)||null;
 const updateSource=(key:string,source:string)=>setOpenDocs(current=>current.map(doc=>doc.key===key?{...doc,source,dirty:true}:doc));
 const close=(key:string)=>{setOpenDocs(current=>{const index=current.findIndex(doc=>doc.key===key),next=current.filter(doc=>doc.key!==key);if(activeKey===key)setActiveKey(next[Math.max(0,index-1)]?.key||next[0]?.key||null);if(compareKey===key)setCompareKey(null);return next})};
 const chooseComparison=()=>{if(compareKey){setCompareKey(null);return}const other=[...openDocs].reverse().find(doc=>doc.key!==activeKey);if(other)setCompareKey(other.key)};
 const saveDoc=async(doc:OpenDocument)=>{setBusy(true);setError(null);try{const document=JSON.parse(doc.source) as DataResource;if(!document.id||!["semantic_datatype","representation_datatype","concrete_datatype"].includes(document.kind))throw new Error("Data resource must declare id and kind=semantic_datatype, representation_datatype, or concrete_datatype");const directory=document.kind==="semantic_datatype"?"datatypes":document.kind==="representation_datatype"?"representations":"concrete_datatypes";const path=workspaceId==="shared"||doc.record.source==="workspace"?doc.record.path:`${directory}/${slug(document.id)}.${document.kind}.json`;await jsonRequest(`/api/workspaces/${encodeURIComponent(workspaceId)}/file`,{method:"PUT",body:JSON.stringify({path,content:JSON.stringify(document,null,2)})});await refresh();setOpenDocs(current=>current.map(item=>item.key===doc.key?{...item,source:JSON.stringify(document,null,2),dirty:false}:item))}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}};

 const renderEditor=(doc:OpenDocument,secondary=false)=>{let document:DataResource|null=null;try{document=doc.source?JSON.parse(doc.source) as DataResource:null}catch{document=null}const datatype=document?.kind==="semantic_datatype"?document:null,representation=document?.kind==="representation_datatype"?document:null,concrete=document?.kind==="concrete_datatype"?document:null,variants=datatype?(byDatatype.get(datatype.id)||[]):[];const concreteVariants=representation?(byRepresentation.get(representation.id)||[]):[];const refs=document?references.filter(ref=>ref.datatype===document!.id||ref.representation===document!.id):[];
  const patchDatatype=(patch:Partial<DatatypeDef>)=>{if(!datatype)return;updateSource(doc.key,JSON.stringify({...datatype,...patch},null,2))};
  const setPreferred=(id:string)=>{if(!datatype)return;const children=datatype.children?.length?datatype.children:variants.map(row=>row.document?.id).filter(Boolean) as string[];patchDatatype({preferredChild:id||undefined,children})};
  const patchRepresentation=(patch:Partial<RepresentationDef>)=>{if(!representation)return;updateSource(doc.key,JSON.stringify({...representation,...patch},null,2))};
  const setPreferredConcrete=(id:string)=>{if(!representation)return;const children=representation.children?.length?representation.children:concreteVariants.map(row=>row.document?.id).filter(Boolean) as string[];patchRepresentation({preferredChild:id||undefined,children})};
  return <section className={`operation-editor-document ${secondary?"secondary":"primary"}`} key={doc.key}><div className="operation-editor-toolbar"><div><span>{datatype?"SEMANTIC DATATYPE":representation?"REPRESENTATION DATATYPE":"CONCRETE DATATYPE"}{doc.dirty?" · UNSAVED":""}</span><h2>{document?.label||document?.id||doc.record.path}</h2><small>{doc.record.source} · {doc.record.path}</small></div><div className="operation-editor-actions">{!secondary&&<button onClick={chooseComparison}>{compareKey?"Single pane":"Split view"}</button>}<button className="primary" disabled={busy||!document} onClick={()=>saveDoc(doc)}>Save</button></div></div><div className="operation-editor-scroll">{!document&&<div className="demo-notice"><b>Invalid resource</b><span>Fix the source before saving.</span></div>}{datatype&&<><div className="operation-abstract-summary"><div><span>PREFERRED REPRESENTATION</span><select value={datatype.preferredChild||""} onChange={e=>setPreferred(e.target.value)}><option value="">planner-selected</option>{variants.map(row=><option key={row.document?.id} value={row.document?.id}>{row.document?.label||row.document?.id}</option>)}</select></div><div><span>ALTERNATIVES</span><code>{variants.length}</code></div><div><span>USED BY</span><code>{refs.length} interfaces</code></div><div><span>EXTENDS</span><code>{datatype.extends?.join(", ")||"—"}</code></div></div><div className="operation-model-list compact">{variants.map(row=>{const child=row.document!,preferred=datatype.preferredChild===child.id;return <button className={`operation-model-option ${preferred?"selected":""}`} key={child.id} onClick={()=>open(row as RecordFile<DataResource>)}><span><b>{child.label||child.id}</b><small>{child.description||`represents ${datatype.id}`}</small></span><em>{preferred?"preferred":"alternative"}</em></button>})}</div></>}{representation&&<div className="implementation-summary"><div><span>PARENTS</span><b>{relationshipIds(representation.parents).join(", ")}</b></div><div><span>PREFERRED CONCRETE</span><select value={representation.preferredChild||""} onChange={e=>setPreferredConcrete(e.target.value)}><option value="">planner-selected</option>{concreteVariants.map(row=><option key={row.document?.id} value={row.document?.id}>{row.document?.label||row.document?.id}</option>)}</select></div><div><span>CONCRETE TYPES</span><b>{concreteVariants.length}</b></div></div>}{concrete&&<div className="implementation-summary"><div><span>PARENTS</span><b>{relationshipIds(concrete.parents).join(", ")}</b></div><div><span>MIME TYPES</span><b>{(concrete.mimeTypes||[]).join(", ")||"?"}</b></div><div><span>EXTENSIONS</span><b>{(concrete.extensions||[]).join(", ")||"?"}</b></div></div>}<ResourceSourceEditor value={doc.source} onChange={value=>updateSource(doc.key,value)} label="Edit this datatype or representation directly" /></div></section>};

 const featured=featuredDatatypes[0]?.document,featuredChildren=featured?(byDatatype.get(featured.id)||[]):[];
 const renderRepresentation=(rep:RecordFile<RepresentationDef>,semantic:DatatypeDef,parentEnablement:ResourceEnablement)=>{const item=rep.document;if(!item)return null;const concretes=byRepresentation.get(item.id)||[],preferred=semantic.preferredChild===item.id,itemEnablement=resolveResourceEnablement(item,parentEnablement);return <ArtifactTreeBranch key={item.id} label={item.label||item.id} searchValue={item} header={<button className={`operation-tree-row operation-child ${enablementClass(itemEnablement)} ${active?.record.document?.id===item.id?"selected":""}`} onClick={()=>open(rep as RecordFile<DataResource>)}><span className="operation-kind-badge llm">REP</span><span><b>{item.label||item.id}</b><small>{item.description||item.id}</small></span><em>{preferred?"preferred ":`${concretes.length} concrete `}<ResourceEnablementBadge state={itemEnablement}/></em></button>}>{concretes.length?concretes.map(row=>{const concrete=row.document!,concreteEnablement=resolveResourceEnablement(concrete,itemEnablement);return <button className={`operation-tree-row operation-child ${enablementClass(concreteEnablement)} ${active?.record.document?.id===concrete.id?"selected":""}`} key={concrete.id} data-tree-search={JSON.stringify(concrete)} onClick={()=>open(row as RecordFile<DataResource>)}><span className="operation-kind-badge">CON</span><span><b>{concrete.label||concrete.id}</b><small>{(concrete.extensions||[]).join(", ")||concrete.id}</small></span><em>{item.preferredChild===concrete.id?"preferred ":""}<ResourceEnablementBadge state={concreteEnablement}/></em></button>}):undefined}</ArtifactTreeBranch>};
 const leftPane=<>{featuredDatatypes.map(row=>{const item=row.document;if(!item)return null;const variants=byDatatype.get(item.id)||[],itemEnablement=resolveResourceEnablement(item);return <ArtifactTreeBranch key={item.id} label={item.label||item.id} searchValue={item} header={<button className={`operation-tree-row operation-parent ${enablementClass(itemEnablement)} ${active?.record.document?.id===item.id?"selected":""}`} onClick={()=>open(row as RecordFile<DataResource>)}><span className="operation-kind-badge">SEM</span><span><b>{item.label||item.id}</b><small>{item.description||item.id}</small></span><em>{variants.length} representations <ResourceEnablementBadge state={itemEnablement}/></em></button>}>{variants.length?variants.map(rep=>renderRepresentation(rep,item,itemEnablement)):undefined}</ArtifactTreeBranch>})}</>
 const tabs=openDocs.map(doc=>({key:doc.key,kind:doc.record.document?.kind==="semantic_datatype"?"SEM":doc.record.document?.kind==="representation_datatype"?"REP":"CON",label:doc.record.document?.label||doc.record.document?.id||doc.record.path,dirty:doc.dirty}));
 const headerActions=<><button className={tab==="types"?"primary":""} onClick={()=>setTab("types")}>Hierarchy</button><button className={tab==="conversions"?"primary":""} onClick={()=>setTab("conversions")}>Conversions</button><button className={tab==="usage"?"primary":""} onClick={()=>setTab("usage")}>Usage</button></>;
 const unresolved=(undeclaredDatatypes.length>0||undeclaredRepresentations.length>0)?<div className="demo-notice"><b>Interface references still need first-class definitions</b><span>{undeclaredDatatypes.length?`Datatypes: ${undeclaredDatatypes.join(", ")}. `:""}{undeclaredRepresentations.length?`Representations: ${undeclaredRepresentations.join(", ")}.`:""}</span></div>:null;
 const notice=<>{featured&&featuredChildren.length>0&&<div className="demo-notice"><b>Alternatives visible now: {featured.label||featured.id}</b><span>{featuredChildren.map(row=>row.document?.label||row.document?.id).join(" · ")}</span></div>}{unresolved}</>;
 if(tab==="conversions")return <section className="resource-view"><div className="resource-heading"><div><span>DATA CONTRACT SYSTEM</span><h1>Representation conversions</h1><p>Conversion operations connect concrete representations of the same abstract datatype.</p></div><div className="studio-actions">{headerActions}</div></div><div className="resource-table"><div className="resource-row resource-head"><span>Conversion operation</span><span>Datatype</span><span>From</span><span>To</span><span>Planning</span></div>{edges.map(edge=><div className="resource-row" key={`${edge.operationId}:${edge.from}:${edge.to}`}><b>{edge.label||edge.operationId}</b><code>{edge.datatype}</code><span>{edge.from}</span><span>{edge.to}</span><em>cost {edge.cost}{edge.lossy?" · lossy":""}</em></div>)}</div></section>;
 if(tab==="usage")return <section className="resource-view"><div className="resource-heading"><div><span>DATA CONTRACT SYSTEM</span><h1>Datatype usage</h1><p>Every operation, prompt, and workflow interface that references a datatype or representation.</p></div><div className="studio-actions">{headerActions}</div></div><div className="resource-table"><div className="resource-row resource-head"><span>Owner</span><span>Kind</span><span>Port</span><span>Datatype</span><span>Representation</span></div>{references.map((ref,index)=><div className="resource-row" key={`${ref.ownerKind}:${ref.ownerId}:${ref.port}:${index}`}><b>{ref.ownerId}</b><code>{ref.ownerKind}</code><span>{ref.direction}:{ref.port}</span><span>{ref.datatype}</span><em>{ref.representation||"planner-selected"}</em></div>)}</div></section>;
 return <HierarchyResourceEditor workspaceId={workspaceId} categoryTree="datatypes" eyebrow="DATA CONTRACT SYSTEM" title="Datatypes & representations" description="Abstract datatypes use the same hierarchy/tree/tab/split-view editor shell as Operations, Prompts, and Models." headerActions={headerActions} notice={notice} error={error} onDismissError={()=>setError(null)} leftPane={leftPane} tabs={tabs} activeKey={activeKey} compareKey={compareKey} onActivate={setActiveKey} onClose={close} renderEditor={(key,secondary)=>{const doc=openDocs.find(item=>item.key===key);return doc?renderEditor(doc,secondary):null}} emptyEditor={<div className="studio-empty">Select a datatype or representation.</div>}/>;
}
