import {useEffect,useMemo,useState} from "react";
import {HierarchyResourceEditor} from "./HierarchyResourceEditor";
import {ArtifactTreeBranch} from "./ArtifactTreeBranch";
import "../styles/operation_editor.css";

type RecordFile<T>={path:string;source?:"shared"|"workspace";workspaceId?:string;document?:T;error?:string};
type DatatypeDef={kind:"datatype";id:string;label?:string;description?:string;extends?:string[];representationSelection?:{default?:string;variants?:string[]};[key:string]:unknown};
type RepresentationDef={kind:"datatype_representation";id:string;label?:string;description?:string;implements:string|string[];[key:string]:unknown};
type DataResource=DatatypeDef|RepresentationDef;
type ConversionEdge={operationId:string;label?:string;datatype:string;from:string;to:string;cost:number;lossy?:boolean;expectedAccuracy?:number};
type InventoryRef={ownerKind:string;ownerId:string;direction:string;port:string;datatype:string;representation?:string|null};
type OpenDocument={key:string;record:RecordFile<DataResource>;source:string;dirty:boolean};

async function jsonRequest(path:string,init?:RequestInit){const response=await fetch(path,{headers:{"Content-Type":"application/json",...(init?.headers||{})},...init});const payload=await response.json();if(!response.ok)throw new Error(String(payload.error||payload.detail||response.statusText));return payload;}
const slug=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"")||"item";
const recordKey=(record:RecordFile<DataResource>)=>`${record.workspaceId||record.source||"resource"}:${record.path}:${record.document?.id||"unknown"}`;
const implementsType=(representation:RepresentationDef,datatypeId:string)=>Array.isArray(representation.implements)?representation.implements.includes(datatypeId):representation.implements===datatypeId;

export function DataCatalogPanel({workspaceId}:{workspaceId:string}){
 const[datatypes,setDatatypes]=useState<RecordFile<DatatypeDef>[]>([]),[representations,setRepresentations]=useState<RecordFile<RepresentationDef>[]>([]),[edges,setEdges]=useState<ConversionEdge[]>([]),[references,setReferences]=useState<InventoryRef[]>([]),[undeclaredDatatypes,setUndeclaredDatatypes]=useState<string[]>([]),[undeclaredRepresentations,setUndeclaredRepresentations]=useState<string[]>([]),[openDocs,setOpenDocs]=useState<OpenDocument[]>([]),[activeKey,setActiveKey]=useState<string|null>(null),[compareKey,setCompareKey]=useState<string|null>(null),[tab,setTab]=useState<"types"|"conversions"|"usage">("types"),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);
 const refresh=async()=>{const[graph,inventory]=await Promise.all([jsonRequest(`/api/workspaces/${encodeURIComponent(workspaceId)}/representation-graph`),jsonRequest(`/api/workspaces/${encodeURIComponent(workspaceId)}/data-inventory`)]);setDatatypes(graph.datatypes||[]);setRepresentations(graph.representations||[]);setEdges(graph.conversionEdges||[]);setReferences(inventory.references||[]);setUndeclaredDatatypes(inventory.undeclaredDatatypes||[]);setUndeclaredRepresentations(inventory.undeclaredRepresentations||[])};
 useEffect(()=>{setOpenDocs([]);setActiveKey(null);setCompareKey(null);setTab("types");void refresh().catch(reason=>setError(String(reason)))},[workspaceId]);
 const byDatatype=useMemo(()=>{const result=new Map<string,RecordFile<RepresentationDef>[]>();for(const datatype of datatypes)result.set(datatype.document?.id||datatype.path,[]);for(const representation of representations){if(!representation.document)continue;for(const datatype of datatypes){const id=datatype.document?.id;if(id&&implementsType(representation.document,id))result.get(id)?.push(representation)}}for(const rows of result.values())rows.sort((a,b)=>String(a.document?.label||a.document?.id||a.path).localeCompare(String(b.document?.label||b.document?.id||b.path)));return result},[datatypes,representations]);
 const featuredDatatypes=useMemo(()=>[...datatypes].sort((a,b)=>{const aid=a.document?.id||"",bid=b.document?.id||"",ac=(byDatatype.get(aid)||[]).length,bc=(byDatatype.get(bid)||[]).length;if(aid==="image"&&bid!=="image")return-1;if(bid==="image"&&aid!=="image")return 1;if(bc!==ac)return bc-ac;return String(a.document?.label||aid||a.path).localeCompare(String(b.document?.label||bid||b.path))}),[datatypes,byDatatype]);
 const open=(record:RecordFile<DataResource>)=>{const key=recordKey(record);setOpenDocs(current=>current.some(doc=>doc.key===key)?current:[...current,{key,record,source:record.document?JSON.stringify(record.document,null,2):"",dirty:false}]);setActiveKey(key)};
 useEffect(()=>{if(openDocs.length===0&&featuredDatatypes[0])open(featuredDatatypes[0] as RecordFile<DataResource>)},[featuredDatatypes]);
 const active=openDocs.find(doc=>doc.key===activeKey)||null;
 const updateSource=(key:string,source:string)=>setOpenDocs(current=>current.map(doc=>doc.key===key?{...doc,source,dirty:true}:doc));
 const close=(key:string)=>{setOpenDocs(current=>{const index=current.findIndex(doc=>doc.key===key),next=current.filter(doc=>doc.key!==key);if(activeKey===key)setActiveKey(next[Math.max(0,index-1)]?.key||next[0]?.key||null);if(compareKey===key)setCompareKey(null);return next})};
 const chooseComparison=()=>{if(compareKey){setCompareKey(null);return}const other=[...openDocs].reverse().find(doc=>doc.key!==activeKey);if(other)setCompareKey(other.key)};
 const saveDoc=async(doc:OpenDocument)=>{setBusy(true);setError(null);try{const document=JSON.parse(doc.source) as DataResource;if(!document.id||!["datatype","datatype_representation"].includes(document.kind))throw new Error("Data resource must declare id and kind=datatype or datatype_representation");const directory=document.kind==="datatype"?"datatypes":"representations";const path=workspaceId==="shared"||doc.record.source==="workspace"?doc.record.path:`${directory}/${slug(document.id)}.${document.kind}.json`;await jsonRequest(`/api/workspaces/${encodeURIComponent(workspaceId)}/file`,{method:"PUT",body:JSON.stringify({path,content:JSON.stringify(document,null,2)})});await refresh();setOpenDocs(current=>current.map(item=>item.key===doc.key?{...item,source:JSON.stringify(document,null,2),dirty:false}:item))}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}};

 const renderEditor=(doc:OpenDocument,secondary=false)=>{let document:DataResource|null=null;try{document=doc.source?JSON.parse(doc.source) as DataResource:null}catch{document=null}const datatype=document?.kind==="datatype"?document:null,representation=document?.kind==="datatype_representation"?document:null,variants=datatype?(byDatatype.get(datatype.id)||[]):[];const refs=document?references.filter(ref=>ref.datatype===document!.id||ref.representation===document!.id):[];
  const patchDatatype=(patch:Partial<DatatypeDef>)=>{if(!datatype)return;updateSource(doc.key,JSON.stringify({...datatype,...patch},null,2))};
  const setPreferred=(id:string)=>{if(!datatype)return;const current=datatype.representationSelection||{};const ids=current.variants?.length?current.variants:variants.map(row=>row.document?.id).filter(Boolean) as string[];patchDatatype({representationSelection:{...current,default:id||undefined,variants:ids}})};
  return <section className={`operation-editor-document ${secondary?"secondary":"primary"}`} key={doc.key}><div className="operation-editor-toolbar"><div><span>{datatype?"ABSTRACT DATATYPE":"DATA REPRESENTATION"}{doc.dirty?" · UNSAVED":""}</span><h2>{document?.label||document?.id||doc.record.path}</h2><small>{doc.record.source} · {doc.record.path}</small></div><div className="operation-editor-actions">{!secondary&&<button onClick={chooseComparison}>{compareKey?"Single pane":"Split view"}</button>}<button className="primary" disabled={busy||!document} onClick={()=>saveDoc(doc)}>Save</button></div></div><div className="operation-editor-scroll">{!document&&<div className="demo-notice"><b>Invalid JSON</b><span>Fix the JSON before saving.</span></div>}{datatype&&<><div className="operation-abstract-summary"><div><span>PREFERRED REPRESENTATION</span><select value={datatype.representationSelection?.default||""} onChange={e=>setPreferred(e.target.value)}><option value="">planner-selected</option>{variants.map(row=><option key={row.document?.id} value={row.document?.id}>{row.document?.label||row.document?.id}</option>)}</select></div><div><span>ALTERNATIVES</span><code>{variants.length}</code></div><div><span>USED BY</span><code>{refs.length} interfaces</code></div><div><span>EXTENDS</span><code>{datatype.extends?.join(", ")||"—"}</code></div></div><div className="operation-model-list compact">{variants.map(row=>{const child=row.document!,preferred=datatype.representationSelection?.default===child.id;return <button className={`operation-model-option ${preferred?"selected":""}`} key={child.id} onClick={()=>open(row as RecordFile<DataResource>)}><span><b>{child.label||child.id}</b><small>{child.description||`implements ${datatype.id}`}</small></span><em>{preferred?"preferred":"alternative"}</em></button>})}</div></>}{representation&&<div className="implementation-summary"><div><span>IMPLEMENTS</span><b>{Array.isArray(representation.implements)?representation.implements.join(", "):representation.implements}</b></div><div><span>USED BY</span><b>{refs.length} interface(s)</b></div></div>}<div className="operation-json-block"><div className="llm-subhead"><div><span>RESOURCE JSON</span><b>Edit this datatype or representation directly</b></div></div><textarea className="raw-json-editor operation-visible-editor" value={doc.source} onChange={e=>updateSource(doc.key,e.target.value)}/></div></div></section>};

 const featured=featuredDatatypes[0]?.document,featuredChildren=featured?(byDatatype.get(featured.id)||[]):[];
 const leftPane=<>{featuredDatatypes.map(row=>{const item=row.document;if(!item)return null;const variants=byDatatype.get(item.id)||[];return <ArtifactTreeBranch key={item.id} label={item.label||item.id} header={<button className={`operation-tree-row operation-parent ${active?.record.document?.id===item.id?"selected":""}`} onClick={()=>open(row as RecordFile<DataResource>)}><span className="operation-kind-badge">TYPE</span><span><b>{item.label||item.id}</b><small>{item.description||item.id}</small></span><em>{variants.length} alternatives</em></button>}>{variants.length?variants.map(rep=>{const child=rep.document!,preferred=item.representationSelection?.default===child.id;return <button className={`operation-tree-row operation-child ${active?.record.document?.id===child.id?"selected":""}`} key={child.id} onClick={()=>open(rep as RecordFile<DataResource>)}><span className="operation-kind-badge llm">REP</span><span><b>{child.label||child.id}</b><small>{child.description||child.id}</small></span><em>{preferred?"preferred":""}</em></button>}):undefined}</ArtifactTreeBranch>})}</>;
 const tabs=openDocs.map(doc=>({key:doc.key,kind:doc.record.document?.kind==="datatype"?"TYPE":"REP",label:doc.record.document?.label||doc.record.document?.id||doc.record.path,dirty:doc.dirty}));
 const headerActions=<><button className={tab==="types"?"primary":""} onClick={()=>setTab("types")}>Hierarchy</button><button className={tab==="conversions"?"primary":""} onClick={()=>setTab("conversions")}>Conversions</button><button className={tab==="usage"?"primary":""} onClick={()=>setTab("usage")}>Usage</button></>;
 const unresolved=(undeclaredDatatypes.length>0||undeclaredRepresentations.length>0)?<div className="demo-notice"><b>Interface references still need first-class definitions</b><span>{undeclaredDatatypes.length?`Datatypes: ${undeclaredDatatypes.join(", ")}. `:""}{undeclaredRepresentations.length?`Representations: ${undeclaredRepresentations.join(", ")}.`:""}</span></div>:null;
 const notice=<>{featured&&featuredChildren.length>0&&<div className="demo-notice"><b>Alternatives visible now: {featured.label||featured.id}</b><span>{featuredChildren.map(row=>row.document?.label||row.document?.id).join(" · ")}</span></div>}{unresolved}</>;
 if(tab==="conversions")return <section className="resource-view"><div className="resource-heading"><div><span>DATA CONTRACT SYSTEM</span><h1>Representation conversions</h1><p>Conversion operations connect concrete representations of the same abstract datatype.</p></div><div className="studio-actions">{headerActions}</div></div><div className="resource-table"><div className="resource-row resource-head"><span>Conversion operation</span><span>Datatype</span><span>From</span><span>To</span><span>Planning</span></div>{edges.map(edge=><div className="resource-row" key={`${edge.operationId}:${edge.from}:${edge.to}`}><b>{edge.label||edge.operationId}</b><code>{edge.datatype}</code><span>{edge.from}</span><span>{edge.to}</span><em>cost {edge.cost}{edge.lossy?" · lossy":""}</em></div>)}</div></section>;
 if(tab==="usage")return <section className="resource-view"><div className="resource-heading"><div><span>DATA CONTRACT SYSTEM</span><h1>Datatype usage</h1><p>Every operation, prompt, and workflow interface that references a datatype or representation.</p></div><div className="studio-actions">{headerActions}</div></div><div className="resource-table"><div className="resource-row resource-head"><span>Owner</span><span>Kind</span><span>Port</span><span>Datatype</span><span>Representation</span></div>{references.map((ref,index)=><div className="resource-row" key={`${ref.ownerKind}:${ref.ownerId}:${ref.port}:${index}`}><b>{ref.ownerId}</b><code>{ref.ownerKind}</code><span>{ref.direction}:{ref.port}</span><span>{ref.datatype}</span><em>{ref.representation||"planner-selected"}</em></div>)}</div></section>;
 return <HierarchyResourceEditor eyebrow="DATA CONTRACT SYSTEM" title="Datatypes & representations" description="Abstract datatypes use the same hierarchy/tree/tab/split-view editor shell as Operations, Prompts, and Models." headerActions={headerActions} notice={notice} error={error} onDismissError={()=>setError(null)} leftPane={leftPane} tabs={tabs} activeKey={activeKey} compareKey={compareKey} onActivate={setActiveKey} onClose={close} renderEditor={(key,secondary)=>{const doc=openDocs.find(item=>item.key===key);return doc?renderEditor(doc,secondary):null}} emptyEditor={<div className="studio-empty">Select a datatype or representation.</div>}/>;
}
