import {useMemo,useRef,useState} from "react";
import {WorkspaceFileRunner} from "./WorkspaceFileRunner";

type WorkspaceFile={path:string;name:string;suffix:string;size:number;modified:number;kind:string};
const imageSuffixes=new Set([".png",".jpg",".jpeg",".gif",".webp",".bmp",".svg"]);
const toBase64=(file:File)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(reader.error||new Error(`Could not read ${file.name}`));reader.onload=()=>resolve(String(reader.result||"").split(",",2)[1]||"");reader.readAsDataURL(file)});

export function KnowledgeDataExplorer({workspaceId,files,onChanged}:{workspaceId:string;files:WorkspaceFile[];onChanged:()=>Promise<unknown>}){
 const inputRef=useRef<HTMLInputElement>(null),[selectedPath,setSelectedPath]=useState(""),[collection,setCollection]=useState("imports"),[overwrite,setOverwrite]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const values=files.filter(file=>/^(knowledge|data|datasets|images|inputs|examples)\//i.test(file.path)&&!/\.md$/i.test(file.path));
 const selected=useMemo(()=>values.find(file=>file.path===selectedPath)||null,[values,selectedPath]);
 const assetUrl=selected?`/workbench/workspaces/${encodeURIComponent(workspaceId)}/asset?path=${encodeURIComponent(selected.path)}`:"";
 const importFiles=async(list:FileList|null)=>{if(!list?.length)return;const collectionId=collection.trim().toLowerCase().replace(/[^a-z0-9._-]+/g,"-").replace(/^-+|-+$/g,"")||"imports";setBusy(true);setError("");try{const uploads=await Promise.all([...list].map(async file=>({name:file.name,base64:await toBase64(file)})));const response=await fetch(`/workbench/workspaces/${encodeURIComponent(workspaceId)}/data/import`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({directory:`knowledge/data/${collectionId}`,files:uploads,overwrite})});const payload=await response.json();if(!response.ok)throw new Error(payload.detail||`Import failed (${response.status})`);setSelectedPath(payload.files?.[0]?.path||"");await onChanged()}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false);if(inputRef.current)inputRef.current.value=""}};
 return <section className="resource-view knowledge-data-explorer"><div className="resource-heading"><div><span>TYPED WORKSPACE CONTENT</span><h1>Data</h1><p>Imported and generated images, text, datasets, demonstrations, and other values. Datatype definitions remain under Capabilities.</p></div><div className="knowledge-data-import"><label><span>COLLECTION</span><input aria-label="Data collection name" value={collection} onChange={event=>setCollection(event.target.value)} placeholder="imports"/></label><label className="knowledge-data-overwrite"><input type="checkbox" checked={overwrite} onChange={event=>setOverwrite(event.target.checked)}/> Replace same-name files</label><button disabled={busy} onClick={()=>inputRef.current?.click()}>{busy?"Importing…":"Import Data"}</button><input ref={inputRef} hidden type="file" multiple onChange={event=>void importFiles(event.target.files)}/></div></div>{error&&<div className="demo-notice"><b>IMPORT FAILED</b><span>{error}</span></div>}<div className="knowledge-data-layout"><div className="resource-table"><div className="resource-row resource-head"><span>VALUE / FILE</span><span>KIND</span><span>FORMAT</span><span>SIZE</span><span>WORKSPACE PATH</span></div>{values.map(file=><button type="button" className={`resource-row ${selectedPath===file.path?"selected":""}`} onClick={()=>setSelectedPath(file.path)} key={file.path}><b>{file.name}</b><code>{file.kind||"data"}</code><span>{file.suffix||"value"}</span><span>{file.size.toLocaleString()} bytes</span><em>{file.path}</em></button>)}{values.length===0&&<div className="studio-empty">No imported Data values yet. Import files here or run a Workflow that produces persistent outputs.</div>}</div>{selected&&<aside className="knowledge-data-preview"><span>SELECTED VALUE</span><h2>{selected.name}</h2>{imageSuffixes.has(selected.suffix.toLowerCase())?<img src={assetUrl} alt={`Preview of ${selected.name}`}/>:<div className="knowledge-data-file-icon">{selected.suffix||"FILE"}</div>}<dl><dt>Path</dt><dd>{selected.path}</dd><dt>Size</dt><dd>{selected.size.toLocaleString()} bytes</dd><dt>Modified</dt><dd>{new Date(selected.modified*1000).toLocaleString()}</dd></dl><a href={assetUrl} target="_blank" rel="noreferrer">Open original</a></aside>}</div>{selected&&<WorkspaceFileRunner workspaceId={workspaceId} file={selected} resourceKind="data"/>}</section>;
}
