import React,{useEffect,useMemo,useState} from "react";
import "../styles/models_editor.css";

type Source="shared"|"workspace";
type NodeKind="backend"|"model"|"profile";
type RecordFile<T>={path:string;source?:Source;workspaceId?:string;document?:T;error?:string;resolved?:Resolution};
type BackendDef={kind:"backend";id:string;label?:string;description?:string;provider:string;official?:boolean;enabled?:boolean;capabilities?:string[];configuration?:Record<string,unknown>;modelDefaults?:Record<string,unknown>};
type ModelDef={kind:"model"|"profile";id:string;label?:string;description?:string;inherits:string;model?:string;enabled?:boolean;capabilities?:string[];defaults?:Record<string,unknown>;environment?:Record<string,unknown>};
type Resolution={parentId?:string;parentKind?:NodeKind;backendId?:string;inheritance?:string[];configuration?:Record<string,unknown>;defaults?:Record<string,unknown>;model?:string;enabled?:boolean};
type Snapshot={backends:RecordFile<BackendDef>[];models:RecordFile<ModelDef>[]};
type Layout="tiles"|"list";
type CatalogItem={kind:NodeKind;id:string;label:string;record:RecordFile<BackendDef>|RecordFile<ModelDef>};

const slug=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"")||"item";
async function request(path:string,init?:RequestInit){const r=await fetch(path,{headers:{"Content-Type":"application/json",...(init?.headers||{})},...init});const p=await r.json();if(!r.ok)throw new Error(p.error||p.detail||r.statusText);return p;}
function isLlmBackend(record:RecordFile<BackendDef>){const item=record.document;if(!item)return false;const caps=(item.capabilities||[]).join(" ").toLowerCase();return caps.includes("llm")||/openai|anthropic|openrouter|groq|ollama|unsloth|llm/.test(item.provider.toLowerCase());}
function num(v:unknown,fallback:number){return typeof v==="number"&&Number.isFinite(v)?v:fallback;}

function ConfigForm({source,onChange,items}:{source:string;onChange:(v:string)=>void;items:CatalogItem[]}){
 const doc=useMemo<ModelDef|null>(()=>{try{return JSON.parse(source) as ModelDef}catch{return null}},[source]);
 if(!doc)return <div className="demo-notice"><b>Invalid JSON</b><span>Fix this item before using the configurator.</span></div>;
 const defaults=doc.defaults||{};const update=(patch:Partial<ModelDef>)=>onChange(JSON.stringify({...doc,...patch},null,2));const updateDefault=(name:string,value:unknown)=>update({defaults:{...defaults,[name]:value}});
 return <div className="model-config-form">
  <label><span>KIND</span><select value={doc.kind} onChange={e=>update({kind:e.target.value as "model"|"profile"})}><option value="model">model</option><option value="profile">profile</option></select></label>
  <label><span>ID</span><input value={doc.id} onChange={e=>update({id:e.target.value})}/></label><label><span>LABEL</span><input value={doc.label||""} onChange={e=>update({label:e.target.value})}/></label>
  <label><span>INHERITS FROM</span><select value={doc.inherits} onChange={e=>update({inherits:e.target.value})}>{items.filter(x=>x.id!==doc.id).map(x=><option key={`${x.kind}:${x.id}`} value={x.id}>{x.kind.toUpperCase()} · {x.label}</option>)}</select></label>
  <label><span>MODEL ID OVERRIDE</span><input value={doc.model||""} placeholder="inherit" onChange={e=>update({model:e.target.value||undefined})}/></label>
  <label><span>TEMPERATURE</span><input type="number" step="0.01" value={num(defaults.temperature,0)} onChange={e=>updateDefault("temperature",Number(e.target.value))}/></label><label><span>TOP P</span><input type="number" step="0.01" value={num(defaults.topP,1)} onChange={e=>updateDefault("topP",Number(e.target.value))}/></label>
  <label><span>MAX OUTPUT TOKENS</span><input type="number" value={num(defaults.maxOutputTokens,12000)} onChange={e=>updateDefault("maxOutputTokens",Number(e.target.value))}/></label><label><span>REASONING EFFORT</span><select value={String(defaults.reasoningEffort||"medium")} onChange={e=>updateDefault("reasoningEffort",e.target.value)}><option>low</option><option>medium</option><option>high</option></select></label>
  <label><span>ANALYSIS LEVEL</span><input type="number" value={num(defaults.analysisLevel,0)} onChange={e=>updateDefault("analysisLevel",Number(e.target.value))}/></label><label><span>TIMEOUT SECONDS</span><input type="number" value={num(defaults.timeoutSeconds,300)} onChange={e=>updateDefault("timeoutSeconds",Number(e.target.value))}/></label>
  <label><span>CURRENT IMAGE DETAIL</span><select value={String(defaults.currentImageDetail||"high")} onChange={e=>updateDefault("currentImageDetail",e.target.value)}><option>low</option><option>high</option></select></label><label><span>PARENT IMAGE DETAIL</span><select value={String(defaults.parentImageDetail||"low")} onChange={e=>updateDefault("parentImageDetail",e.target.value)}><option>low</option><option>high</option></select></label>
  <label className="model-enable-field"><span>AVAILABLE TO TASKS</span><input type="checkbox" checked={doc.enabled!==false} onChange={e=>update({enabled:e.target.checked})}/></label>
 </div>;
}

export function LlmModelsEditor({workspaceId}:{workspaceId:string}){
 const[snapshot,setSnapshot]=useState<Snapshot|null>(null),[layout,setLayout]=useState<Layout>("tiles"),[selected,setSelected]=useState<RecordFile<ModelDef>|null>(null),[source,setSource]=useState(""),[target,setTarget]=useState<string|null>(null),[selectedBackend,setSelectedBackend]=useState<RecordFile<BackendDef>|null>(null),[backendSource,setBackendSource]=useState(""),[backendTarget,setBackendTarget]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const load=async()=>{const next=await request(`/api/workspaces/${encodeURIComponent(workspaceId)}/snapshot`) as Snapshot;setSnapshot(next);return next};useEffect(()=>{setSelected(null);setSelectedBackend(null);void load().catch(r=>setError(String(r)))},[workspaceId]);
 const backends=useMemo(()=>(snapshot?.backends||[]).filter(isLlmBackend),[snapshot]);const nodes=snapshot?.models||[];
 const items=useMemo<CatalogItem[]>(()=>[...backends.filter(x=>x.document).map(record=>({kind:"backend" as const,id:record.document!.id,label:record.document!.label||record.document!.id,record})),...nodes.filter(x=>x.document).map(record=>({kind:record.document!.kind,id:record.document!.id,label:record.document!.label||record.document!.id,record}))],[backends,nodes]);
 const children=useMemo(()=>{const map=new Map<string,RecordFile<ModelDef>[]>();for(const record of nodes){const parent=record.document?.inherits;if(!parent)continue;const rows=map.get(parent)||[];rows.push(record);map.set(parent,rows)}return map},[nodes]);
 const perform=async(work:()=>Promise<void>)=>{setBusy(true);setError(null);try{await work()}catch(r){setError(r instanceof Error?r.message:String(r))}finally{setBusy(false)}};
 const openNode=(r:RecordFile<ModelDef>)=>{setSelected(r);setSelectedBackend(null);setSource(r.document?JSON.stringify(r.document,null,2):"");setTarget(workspaceId==="shared"||r.source==="workspace"?r.path:null)};const openBackend=(r:RecordFile<BackendDef>)=>{setSelectedBackend(r);setSelected(null);setBackendSource(r.document?JSON.stringify(r.document,null,2):"");setBackendTarget(workspaceId==="shared"||r.source==="workspace"?r.path:null)};
 useEffect(()=>{if(snapshot&&!selected&&!selectedBackend){if(nodes[0])openNode(nodes[0]);else if(backends[0])openBackend(backends[0])}},[snapshot]);
 const saveNode=()=>perform(async()=>{const doc=JSON.parse(source) as ModelDef;if(!["model","profile"].includes(doc.kind)||!doc.id||!doc.inherits)throw new Error("Model/profile requires kind, id, and inherits");if("prompt_text" in doc||"prompts" in doc)throw new Error("Prompt lists belong on Tasks, not model profiles");const path=target||`models/${slug(doc.id)}.json`;await request(`/api/workspaces/${encodeURIComponent(workspaceId)}/file`,{method:"PUT",body:JSON.stringify({path,content:JSON.stringify(doc,null,2)})});const next=await load();const saved=next.models.find(x=>x.document?.id===doc.id);if(saved)openNode(saved)});
 const newChild=(parent:CatalogItem,kind:"model"|"profile")=>{const id=`${parent.id}-${kind}`;const doc:ModelDef={kind,id,label:`${parent.label} ${kind}`,inherits:parent.id,enabled:true,defaults:{temperature:0,topP:1,maxOutputTokens:12000,reasoningEffort:"medium",timeoutSeconds:300}};setSelected({path:`models/${slug(id)}.json`,source:workspaceId==="shared"?"shared":"workspace",workspaceId,document:doc});setSelectedBackend(null);setSource(JSON.stringify(doc,null,2));setTarget(`models/${slug(id)}.json`)};
 const cloneProfile=()=>{if(!selected?.document)return;newChild({kind:selected.document.kind,id:selected.document.id,label:selected.document.label||selected.document.id,record:selected},"profile")};
 const saveBackend=()=>perform(async()=>{const doc=JSON.parse(backendSource) as BackendDef;if(doc.kind!=="backend"||!doc.id||!doc.provider)throw new Error("Backend requires kind, id, provider");const path=backendTarget||`models/backend_${slug(doc.id)}.json`;await request(`/api/workspaces/${encodeURIComponent(workspaceId)}/file`,{method:"PUT",body:JSON.stringify({path,content:JSON.stringify(doc,null,2)})});const next=await load();const saved=next.backends.find(x=>x.document?.id===doc.id);if(saved)openBackend(saved)});
 const render=(item:CatalogItem,depth=0):JSX.Element=>{const backend=item.kind==="backend";const record=!backend?item.record as RecordFile<ModelDef>:null;const nested=children.get(item.id)||[];return <div className={`inheritance-node ${layout} ${item.kind}-node`} key={`${item.kind}:${item.id}`} style={{"--tree-depth":depth} as React.CSSProperties}><div className="inheritance-row"><button className="inheritance-main" onClick={()=>backend?openBackend(item.record as RecordFile<BackendDef>):openNode(record!)}><span>{item.kind.toUpperCase()}</span><b>{item.label}</b><small>{backend?(item.record as RecordFile<BackendDef>).document?.provider:(record?.resolved?.model||record?.document?.model||`inherits ${record?.document?.inherits}`)}</small>{!backend&&<em>temp {String((record?.resolved?.defaults||record?.document?.defaults||{}).temperature??"—")}</em>}</button><button className="hier-mini" onClick={()=>newChild(item,"model")}>+ model</button><button className="hier-mini" onClick={()=>newChild(item,"profile")}>+ profile</button></div>{nested.length>0&&<div className="inheritance-children">{nested.map(r=>render({kind:r.document!.kind,id:r.document!.id,label:r.document!.label||r.document!.id,record:r},depth+1))}</div>}</div>};
 if(!snapshot)return <section className="resource-view"><div className="studio-empty">Loading model catalog…</div></section>;
 const roots=backends.filter(x=>x.document).map(record=>({kind:"backend" as const,id:record.document!.id,label:record.document!.label||record.document!.id,record}));
 return <section className="resource-view llm-model-editor"><div className="resource-heading"><div><span>MODEL CATALOG</span><h1>Backends, models & profiles</h1><p>Profiles are prompt-free execution presets in the same inheritance graph. Prompt composition belongs to Tasks.</p></div><div className="layout-switch"><button className={layout==="tiles"?"active":""} onClick={()=>setLayout("tiles")}>▦ Tiles</button><button className={layout==="list"?"active":""} onClick={()=>setLayout("list")}>☷ List</button></div></div>{error&&<div className="demo-notice"><b>Configuration error</b><span>{error}</span></div>}<div className={`inheritance-tree ${layout}`}>{roots.map(root=>render(root))}</div>
 {selected&&<section className="model-editor-drawer"><div className="drawer-heading"><div><span>{selected.document?.kind==="profile"?"PROFILE CONFIGURATOR":"MODEL CONFIGURATOR"}</span><h2>{selected.document?.label||selected.document?.id}</h2><small>{selected.source} · {selected.path}</small></div><div><button onClick={cloneProfile}>Clone child profile</button><button className="primary" disabled={busy} onClick={saveNode}>Save</button></div></div><ConfigForm source={source} onChange={setSource} items={items}/><details><summary>Raw JSON</summary><textarea className="raw-json-editor" value={source} onChange={e=>setSource(e.target.value)}/></details><aside className="resolved-inheritance"><span>RESOLVED INHERITANCE</span><pre>{JSON.stringify(selected.resolved||{},null,2)}</pre></aside></section>}
 {selectedBackend?.document&&<section className="model-editor-drawer"><div className="drawer-heading"><div><span>BACKEND CONFIGURATOR</span><h2>{selectedBackend.document.label||selectedBackend.document.id}</h2><small>{selectedBackend.source} · {selectedBackend.path}</small></div><div><button onClick={()=>newChild({kind:"backend",id:selectedBackend.document!.id,label:selectedBackend.document!.label||selectedBackend.document!.id,record:selectedBackend},"model")}>+ Model</button><button onClick={()=>newChild({kind:"backend",id:selectedBackend.document!.id,label:selectedBackend.document!.label||selectedBackend.document!.id,record:selectedBackend},"profile")}>+ Profile</button><button className="primary" disabled={busy} onClick={saveBackend}>Save backend</button></div></div><textarea className="raw-json-editor" value={backendSource} onChange={e=>setBackendSource(e.target.value)}/></section>}</section>;
}
