import { useEffect, useMemo, useState } from "react";
import "../styles/models_editor.css";

type Source = "shared" | "workspace";
type RecordFile<T> = { path:string; source?:Source; workspaceId?:string; document?:T; error?:string; resolved?:ModelResolution };
type BackendDef = { kind:"backend"; id:string; label?:string; description?:string; provider:string; official?:boolean; enabled?:boolean; capabilities?:string[]; configuration?:Record<string,unknown>; modelDefaults?:Record<string,unknown> };
type ModelDef = { kind:"model"; id:string; label?:string; description?:string; backend:string; model:string; enabled?:boolean; capabilities?:string[]; defaults?:Record<string,unknown>; environment?:Record<string,unknown> };
type ModelResolution = { backendId:string; backendSource?:Source; backendPath?:string; backend?:BackendDef|null; configuration?:Record<string,unknown>; defaults?:Record<string,unknown>; enabled?:boolean };
type Library<T> = { shared:RecordFile<T>[]; workspace:RecordFile<T>[]; effective:RecordFile<T>[] };
type Snapshot = { workspace:{id:string;label:string;root:string}; backends:RecordFile<BackendDef>[]; backendLibrary?:Library<BackendDef>; models:RecordFile<ModelDef>[]; modelLibrary?:Library<ModelDef> };
type Layout = "tiles"|"list";
type Section = "models"|"backends";

const slug=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"")||"model";
async function request(path:string,init?:RequestInit){const response=await fetch(path,{headers:{"Content-Type":"application/json",...(init?.headers||{})},...init});const payload=await response.json();if(!response.ok)throw new Error(payload.error||payload.detail||response.statusText);return payload;}
function isLlmBackend(record:RecordFile<BackendDef>){const item=record.document;if(!item)return false;const caps=(item.capabilities||[]).join(" ").toLowerCase();return caps.includes("llm")||/openai|anthropic|openrouter|groq|ollama|unsloth|llm/.test(item.provider.toLowerCase());}
function num(value:unknown,fallback:number){return typeof value==="number"&&Number.isFinite(value)?value:fallback;}

function ModelForm({source,onChange,backends}:{source:string;onChange:(value:string)=>void;backends:RecordFile<BackendDef>[]}){
 const document=useMemo<ModelDef|null>(()=>{try{return JSON.parse(source) as ModelDef}catch{return null}},[source]);
 if(!document)return <div className="demo-notice"><b>Invalid model JSON</b><span>Fix the JSON before using the structured configurator.</span></div>;
 const defaults=document.defaults||{};const update=(patch:Partial<ModelDef>)=>onChange(JSON.stringify({...document,...patch},null,2));const updateDefault=(name:string,value:unknown)=>update({defaults:{...defaults,[name]:value}});
 return <div className="model-config-form">
  <label><span>ID</span><input value={document.id} onChange={e=>update({id:e.target.value})}/></label><label><span>LABEL</span><input value={document.label||""} onChange={e=>update({label:e.target.value})}/></label>
  <label><span>BACKEND</span><select value={document.backend} onChange={e=>update({backend:e.target.value})}>{backends.filter(x=>x.document).map(x=><option key={`${x.workspaceId}:${x.path}`} value={x.document!.id}>{x.document!.label||x.document!.id}</option>)}</select></label><label><span>MODEL ID</span><input value={document.model} onChange={e=>update({model:e.target.value})}/></label>
  <label><span>TEMPERATURE</span><input type="number" step="0.01" value={num(defaults.temperature,0)} onChange={e=>updateDefault("temperature",Number(e.target.value))}/></label><label><span>TOP P</span><input type="number" step="0.01" value={num(defaults.topP,1)} onChange={e=>updateDefault("topP",Number(e.target.value))}/></label>
  <label><span>MAX OUTPUT TOKENS</span><input type="number" step="1" value={num(defaults.maxOutputTokens,12000)} onChange={e=>updateDefault("maxOutputTokens",Number(e.target.value))}/></label><label><span>REASONING EFFORT</span><select value={String(defaults.reasoningEffort||"medium")} onChange={e=>updateDefault("reasoningEffort",e.target.value)}><option>low</option><option>medium</option><option>high</option></select></label>
  <label><span>TIMEOUT SECONDS</span><input type="number" step="1" value={num(defaults.timeoutSeconds,300)} onChange={e=>updateDefault("timeoutSeconds",Number(e.target.value))}/></label><label><span>CURRENT IMAGE DETAIL</span><select value={String(defaults.currentImageDetail||"high")} onChange={e=>updateDefault("currentImageDetail",e.target.value)}><option>low</option><option>high</option></select></label><label><span>PARENT IMAGE DETAIL</span><select value={String(defaults.parentImageDetail||"low")} onChange={e=>updateDefault("parentImageDetail",e.target.value)}><option>low</option><option>high</option></select></label>
  <label className="model-enable-field"><span>AVAILABLE TO TASKS</span><input type="checkbox" checked={document.enabled!==false} onChange={e=>update({enabled:e.target.checked})}/></label>
 </div>;
}

export function LlmModelsEditor({workspaceId}:{workspaceId:string}){
 const[snapshot,setSnapshot]=useState<Snapshot|null>(null),[section,setSection]=useState<Section>("models"),[layout,setLayout]=useState<Layout>("tiles");
 const[selectedModel,setSelectedModel]=useState<RecordFile<ModelDef>|null>(null),[modelSource,setModelSource]=useState(""),[modelTarget,setModelTarget]=useState<string|null>(null);
 const[selectedBackend,setSelectedBackend]=useState<RecordFile<BackendDef>|null>(null),[backendSource,setBackendSource]=useState(""),[backendTarget,setBackendTarget]=useState<string|null>(null);
 const[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const load=async()=>{const next=await request(`/api/workspaces/${encodeURIComponent(workspaceId)}/snapshot`) as Snapshot;setSnapshot(next);return next};useEffect(()=>{void load().catch(reason=>setError(String(reason)))},[workspaceId]);
 const effectiveBackends=useMemo(()=>(snapshot?.backends||[]).filter(isLlmBackend),[snapshot]);const models=snapshot?.models||[];const sharedModels=snapshot?.modelLibrary?.shared||models.filter(x=>x.source==="shared");const workspaceModels=snapshot?.modelLibrary?.workspace||models.filter(x=>x.source==="workspace");
 const grouped=useMemo(()=>effectiveBackends.map(backend=>({backend,models:models.filter(model=>model.document?.backend===backend.document?.id)})),[effectiveBackends,models]);
 const perform=async(work:()=>Promise<void>)=>{setBusy(true);setError(null);try{await work()}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}};
 const openModel=(record:RecordFile<ModelDef>)=>{setSelectedModel(record);setModelSource(record.document?JSON.stringify(record.document,null,2):"");setModelTarget(workspaceId==="shared"||record.source==="workspace"?record.path:null)};
 const openBackend=(record:RecordFile<BackendDef>)=>{setSelectedBackend(record);setBackendSource(record.document?JSON.stringify(record.document,null,2):"");setBackendTarget(workspaceId==="shared"||record.source==="workspace"?record.path:null)};
 useEffect(()=>{if(!snapshot)return;if(!selectedModel&&models[0])openModel(models[0]);if(!selectedBackend&&effectiveBackends[0])openBackend(effectiveBackends[0])},[snapshot]);
 const saveModel=()=>perform(async()=>{const document=JSON.parse(modelSource) as ModelDef;if(document.kind!=="model"||!document.id||!document.backend||!document.model)throw new Error("Model requires kind, id, backend, and model");const path=modelTarget||`models/${slug(document.id)}.json`;await request(`/api/workspaces/${encodeURIComponent(workspaceId)}/file`,{method:"PUT",body:JSON.stringify({path,content:JSON.stringify(document,null,2)})});const next=await load();const saved=next.models.find(x=>x.document?.id===document.id);if(saved)openModel(saved)});
 const copyLocal=(record=selectedModel)=>{if(!record?.document||workspaceId==="shared")return;const document={...record.document};setSelectedModel({...record,source:"workspace",workspaceId,path:`models/${slug(document.id)}.json`,document});setModelSource(JSON.stringify(document,null,2));setModelTarget(`models/${slug(document.id)}.json`)};
 const cloneVariant=(record=selectedModel)=>{if(!record?.document)return;const base=record.document;const id=`${base.id}-variant`;const document:ModelDef={...base,id,label:`${base.label||base.id} variant`};setSelectedModel({...record,source:workspaceId==="shared"?"shared":"workspace",workspaceId,path:`models/${slug(id)}.json`,document});setModelSource(JSON.stringify(document,null,2));setModelTarget(`models/${slug(id)}.json`)};
 const newModelForBackend=(backend:RecordFile<BackendDef>)=>{if(!backend.document)return;const id=`${backend.document.id}-model`;const defaults=backend.document.modelDefaults||{temperature:0,topP:1,maxOutputTokens:12000,reasoningEffort:"medium",timeoutSeconds:300};const document:ModelDef={kind:"model",id,label:`${backend.document.label||backend.document.id} model`,backend:backend.document.id,model:String((backend.document.configuration||{}).defaultModel||""),enabled:true,defaults};setSelectedModel({path:`models/${slug(id)}.json`,source:workspaceId==="shared"?"shared":"workspace",workspaceId,document});setModelSource(JSON.stringify(document,null,2));setModelTarget(`models/${slug(id)}.json`)};
 const saveBackend=()=>perform(async()=>{const document=JSON.parse(backendSource) as BackendDef;if(document.kind!=="backend"||!document.id||!document.provider)throw new Error("Backend requires kind, id, and provider");const path=backendTarget||`backends/${slug(document.id)}.json`;await request(`/api/workspaces/${encodeURIComponent(workspaceId)}/file`,{method:"PUT",body:JSON.stringify({path,content:JSON.stringify(document,null,2)})});const next=await load();const saved=next.backends.find(x=>x.document?.id===document.id);if(saved)openBackend(saved)});
 const copyBackendLocal=()=>{if(!selectedBackend?.document||workspaceId==="shared")return;const document={...selectedBackend.document,official:false};setBackendSource(JSON.stringify(document,null,2));setBackendTarget(`backends/${slug(document.id)}.json`)};
 const modelCard=(record:RecordFile<ModelDef>)=>{if(!record.document)return null;const item=record.document,enabled=record.resolved?.enabled??item.enabled!==false,defaults=record.resolved?.defaults||item.defaults||{};return <div key={`${record.workspaceId}:${record.path}`} className={`hier-model ${layout} ${selectedModel?.document?.id===item.id?"selected":""} ${enabled?"":"disabled"}`}><button className="hier-model-main" onClick={()=>openModel(record)}><span className="hier-source">{record.source==="workspace"?"WORKSPACE":"SHARED"}</span><b>{item.label||item.id}</b><small>{item.model}</small><p>{item.description||"Model configuration inheriting its provider backend."}</p><div className="hier-model-meta"><span>temp {String(defaults.temperature??"—")}</span><span>top-p {String(defaults.topP??"—")}</span><span>{String(defaults.reasoningEffort||"—")}</span><span>{enabled?"enabled":"disabled"}</span></div></button>{record.source==="shared"&&workspaceId!=="shared"&&<button className="hier-mini" onClick={()=>copyLocal(record)}>Customize</button>}</div>};
 if(!snapshot)return <section className="resource-view"><div className="studio-empty">Loading model library…</div></section>;
 return <section className="resource-view llm-model-editor"><div className="resource-heading"><div><span>MODEL CONFIGURATION</span><h1>Models & backends</h1><p>A backend owns connectivity and provider defaults. Models inherit that backend and specialize model ID, temperature, reasoning, token budget, vision detail, timeout, and task availability.</p></div><div className="llm-section-switch"><button className={section==="models"?"active":""} onClick={()=>setSection("models")}>Models</button><button className={section==="backends"?"active":""} onClick={()=>setSection("backends")}>Backends</button></div></div>{error&&<div className="demo-notice"><b>Configuration error</b><span>{error}</span></div>}
 {section==="models"&&<><div className="models-toolbar"><div><b>Hierarchical model library</b><small>{sharedModels.length} shared · {workspaceModels.length} workspace overrides · {models.length} effective</small></div><div className="layout-switch"><button className={layout==="tiles"?"active":""} onClick={()=>setLayout("tiles")}>▦ Tiles</button><button className={layout==="list"?"active":""} onClick={()=>setLayout("list")}>☷ List</button></div></div><div className={`backend-model-tree ${layout}`}>{grouped.map(group=>{const backend=group.backend.document!;return <section className="backend-family" key={`${group.backend.workspaceId}:${group.backend.path}`}><header className="backend-family-head"><button className="backend-parent" onClick={()=>{openBackend(group.backend);setSection("backends")}}><span>BACKEND</span><b>{backend.label||backend.id}</b><small>{backend.provider} · {group.backend.source}</small></button><div><span>{group.models.length} models</span><button onClick={()=>newModelForBackend(group.backend)}>+ Model</button></div></header><div className={`backend-children ${layout}`}>{group.models.length?group.models.map(modelCard):<div className="empty-model-family">No model configurations yet for this backend.</div>}</div></section>})}</div>{selectedModel&&<section className="model-editor-drawer"><div className="drawer-heading"><div><span>MODEL CONFIGURATOR</span><h2>{selectedModel.document?.label||selectedModel.document?.id}</h2><small>{selectedModel.source} · {selectedModel.path}</small></div><div>{selectedModel.source==="shared"&&workspaceId!=="shared"&&<button onClick={()=>copyLocal()}>Make workspace-specific</button>}<button onClick={()=>cloneVariant()}>Clone variant</button><button className="primary" disabled={busy} onClick={saveModel}>Save model</button></div></div><ModelForm source={modelSource} onChange={setModelSource} backends={effectiveBackends}/><details><summary>Raw JSON</summary><textarea className="raw-json-editor" value={modelSource} onChange={e=>setModelSource(e.target.value)}/></details><aside className="resolved-inheritance"><span>RESOLVED INHERITANCE</span><pre>{JSON.stringify(selectedModel.resolved||{},null,2)}</pre></aside></section>}</>}
 {section==="backends"&&<><div className="models-toolbar"><div><b>Backend providers</b><small>Connectivity, credentials, endpoints and inherited model defaults.</small></div></div><div className="backend-config-grid">{effectiveBackends.map(record=><button className={`backend-config-card ${selectedBackend?.document?.id===record.document?.id?"selected":""}`} key={`${record.workspaceId}:${record.path}`} onClick={()=>openBackend(record)}><span>{record.source==="workspace"?"WORKSPACE BACKEND":"SHARED BACKEND"}</span><b>{record.document?.label||record.document?.id}</b><small>{record.document?.provider}</small><p>{record.document?.description||"Provider backend"}</p><em>{record.document?.enabled===false?"disabled":"enabled"} · {(record.document?.capabilities||[]).join(", ")}</em></button>)}</div>{selectedBackend?.document&&<section className="model-editor-drawer"><div className="drawer-heading"><div><span>BACKEND CONFIGURATOR</span><h2>{selectedBackend.document.label||selectedBackend.document.id}</h2><small>{selectedBackend.source} · {selectedBackend.path}</small></div><div>{selectedBackend.source==="shared"&&workspaceId!=="shared"&&<button onClick={copyBackendLocal}>Make workspace-specific</button>}<button className="primary" disabled={busy} onClick={saveBackend}>Save backend</button></div></div><div className="backend-inheritance-summary"><div><span>PROVIDER</span><b>{selectedBackend.document.provider}</b></div><div><span>CONFIGURATION</span><pre>{JSON.stringify(selectedBackend.document.configuration||{},null,2)}</pre></div><div><span>MODEL DEFAULTS</span><pre>{JSON.stringify(selectedBackend.document.modelDefaults||{},null,2)}</pre></div></div><textarea className="raw-json-editor" value={backendSource} onChange={e=>setBackendSource(e.target.value)}/></section>}</>}
 </section>;
}
