import {useEffect,useMemo,useState} from "react";
import {OperationPlayground} from "./OperationPlayground";
import {DEFAULT_TREE_VISIBILITY_RULES,type TreeVisibilityRules,useArtifactTreeFilter} from "./useArtifactTreeFilter";
import {RepeatSwitch,TreeViewControls} from "./TreeViewControls";
import {relationshipIds} from "./resourceRelationships";
import {CategorizedArtifactTree,categoryPaths} from "./CategorizedArtifactTree";
import type {ArtifactTreeCommand} from "./ArtifactTreeBranch";
import {ResourceSourceEditor} from "./ResourceSourceEditor";
import {ResourceEnablementBadge,enablementClass,resolveResourceEnablement} from "./resourceEnablement";
import {displayResourcePath} from "./resourcePath";
import {jsonValueToMetta} from "../lib/mettaResourceCodec";
import "../styles/operation_editor.css";

type Source="shared"|"workspace";
type ModelStrategy="single"|"parallel"|"compare"|"fallback";
type RecordFile<T>={path:string;source?:Source;workspaceId?:string;document?:T;error?:string;resolved?:{enabled?:boolean;backendId?:string;defaults?:Record<string,unknown>;model?:string}};
type OperationDef={kind:"operation";id:string;parents?:string[];label?:string;description?:string;categories?:string[];enabled?:boolean;role?:string;implementation?:string;inputs?:Record<string,string>;outputs?:Record<string,string>;children?:string[];preferredChild?:string};
type OperationImplementationDef={kind:"operation";id:string;parents:string[];label?:string;description?:string;categories?:string[];enabled?:boolean;implementation:string;inputs?:Record<string,string>;outputs?:Record<string,string>;parameters?:Record<string,unknown>;bindings?:Record<string,unknown>;python?:Record<string,unknown>;prolog?:Record<string,unknown>;metta?:Record<string,unknown>;modelSelection?:{models?:string[];strategy?:ModelStrategy}};
type OperationResource=OperationDef|OperationImplementationDef;
type ModelDef={kind:"model";id:string;label?:string;parents:string[];model?:string;enabled?:boolean;defaults?:Record<string,unknown>};
type PromptDef={kind:"prompt";id:string;label?:string;description?:string;text?:string|string[];variables?:string[]};
type PromptProfileDef={kind:"prompt_profile";id:string;label?:string;description?:string;prompts:string[];separator?:string};
type Snapshot={workspace:{id:string;label:string;root:string};operations:RecordFile<OperationDef>[];operationImplementations:RecordFile<OperationImplementationDef>[];models:RecordFile<ModelDef>[];prompts:RecordFile<PromptDef>[];promptLibrary?:{hierarchy?:{promptProfiles?:RecordFile<PromptProfileDef>[]}}};
type OpenDocument={key:string;record:RecordFile<OperationResource>;source:string;dirty:boolean};

const slug=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"")||"resource";
const recordKey=(record:RecordFile<OperationResource>)=>`${record.workspaceId||record.source||"resource"}:${record.path}:${record.document?.id||"unknown"}`;
const appearanceCategoryPath=(appearanceKey:string,itemId:string)=>{const prefix="category:";const suffix=`:${itemId}`;return appearanceKey.startsWith(prefix)&&appearanceKey.endsWith(suffix)?appearanceKey.slice(prefix.length,-suffix.length):null};
async function request(path:string,init?:RequestInit){const r=await fetch(path,{headers:{"Content-Type":"application/json",...(init?.headers||{})},...init});const text=await r.text();let p:any;try{p=JSON.parse(text)}catch{throw new Error(text||r.statusText)}if(!r.ok)throw new Error(p.error||p.detail||r.statusText);return p;}

type SourceLanguage="prolog"|"metta"|"python";
export function OperationLibraryEditor({workspaceId,sourceLanguage}:{workspaceId:string;sourceLanguage?:SourceLanguage}){
 const[snapshot,setSnapshot]=useState<Snapshot|null>(null),[openDocs,setOpenDocs]=useState<OpenDocument[]>([]),[activeKey,setActiveKey]=useState<string|null>(null),[compareKey,setCompareKey]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[navigatorCollapsed,setNavigatorCollapsed]=useState(false),[viewControlsOpen,setViewControlsOpen]=useState(false),[collapsedOperations,setCollapsedOperations]=useState<Set<string>>(()=>new Set());
 const[categoryCommand,setCategoryCommand]=useState<ArtifactTreeCommand>(null),[visibilityRules,setVisibilityRules]=useState<TreeVisibilityRules>(DEFAULT_TREE_VISIBILITY_RULES);
 const {treeRef,treeFilter,setTreeFilter,showParents,setShowParents,treeKinds}=useArtifactTreeFilter(visibilityRules);
 const load=async()=>{const next=await request(`/api/workspaces/${encodeURIComponent(workspaceId)}/snapshot`) as Snapshot;setSnapshot(next);return next};
 useEffect(()=>{setOpenDocs([]);setActiveKey(null);setCompareKey(null);void load().catch(r=>setError(String(r)))},[workspaceId]);
 const enabledModels=(snapshot?.models||[]).filter(row=>row.document&&(row.resolved?.enabled??row.document.enabled!==false));
 const prompts=snapshot?.prompts||[];
 const promptProfiles=snapshot?.promptLibrary?.hierarchy?.promptProfiles||[];
 const allImplementations=snapshot?.operationImplementations||[];
 const implementations=useMemo(()=>sourceLanguage?allImplementations.filter(row=>row.document?.implementation?.startsWith(sourceLanguage)):allImplementations,[allImplementations,sourceLanguage]);
 const children=useMemo(()=>{const map=new Map<string,RecordFile<OperationImplementationDef>[]>();for(const row of implementations){for(const id of relationshipIds(row.document?.parents)){const list=map.get(id)||[];list.push(row);map.set(id,list)}}return map},[implementations]);
 const perform=async(work:()=>Promise<void>)=>{setBusy(true);setError(null);try{await work()}catch(r){setError(r instanceof Error?r.message:String(r))}finally{setBusy(false)}};
 const open=(record:RecordFile<OperationResource>)=>{const key=recordKey(record);setOpenDocs(current=>current.some(doc=>doc.key===key)?current:[...current,{key,record,source:record.document?JSON.stringify(record.document,null,2):"",dirty:false}]);setActiveKey(key)};
 const close=(key:string)=>{setOpenDocs(current=>{const index=current.findIndex(doc=>doc.key===key);const next=current.filter(doc=>doc.key!==key);if(activeKey===key)setActiveKey(next[Math.max(0,index-1)]?.key||next[0]?.key||null);if(compareKey===key)setCompareKey(null);return next})};
 useEffect(()=>{if(snapshot&&openDocs.length===0){const requestedId=new URLSearchParams(window.location.search).get("resource");const visibleParents=(snapshot.operations||[]).filter(row=>row.document&&(!sourceLanguage||implementations.some(impl=>relationshipIds(impl.document?.parents).includes(row.document!.id))||row.document.implementation?.startsWith(sourceLanguage)));const allResources:RecordFile<OperationResource>[]=[...visibleParents,...implementations];const featured=allResources.find(row=>row.document?.id===requestedId)||(!sourceLanguage?visibleParents.find(row=>row.document?.id==="echo_into_titlecased"):undefined)||implementations[0]||visibleParents[0];if(featured)open(featured as RecordFile<OperationResource>)}},[snapshot,sourceLanguage,implementations.length]);
 const updateSource=(key:string,source:string)=>setOpenDocs(current=>current.map(doc=>doc.key===key?{...doc,source,dirty:true}:doc));
 const active=openDocs.find(doc=>doc.key===activeKey)||null;
 const comparison=openDocs.find(doc=>doc.key===compareKey)||null;
 const chooseComparison=()=>{if(compareKey){setCompareKey(null);return}const other=[...openDocs].reverse().find(doc=>doc.key!==activeKey);if(other)setCompareKey(other.key)};
 const saveDoc=(doc:OpenDocument)=>perform(async()=>{let document:OperationResource;try{document=JSON.parse(doc.source) as OperationResource}catch{throw new Error("Operation resource source is invalid")};if(document.kind!=="operation")throw new Error("Operation resource requires kind='operation'");const original=doc.record.path;const path=workspaceId==="shared"||doc.record.source==="workspace"?original:`design/operations/${slug(document.id)}.operation.json`;await request(`/api/workspaces/${encodeURIComponent(workspaceId)}/file`,{method:"PUT",body:JSON.stringify({path,content:JSON.stringify(document,null,2)})});const next=await load();const pool:RecordFile<OperationResource>[]=[...(next.operations||[]),...(next.operationImplementations||[])];const saved=pool.find(row=>row.document?.id===document.id);if(saved){const newKey=recordKey(saved);setOpenDocs(current=>current.map(item=>item.key===doc.key?{key:newKey,record:saved,source:JSON.stringify(saved.document,null,2),dirty:false}:item));if(activeKey===doc.key)setActiveKey(newKey);if(compareKey===doc.key)setCompareKey(newKey)}});

 const renderEditor=(doc:OpenDocument,secondary=false)=>{let document:OperationResource|null=null;try{document=doc.source?JSON.parse(doc.source) as OperationResource:null}catch{document=null}const isImplementation=Boolean(document&&relationshipIds(document.parents).length);const abstract=document&&!isImplementation?document as OperationDef:null;const selectedImplementation=document&&isImplementation?document as OperationImplementationDef:null;const parentOperation=selectedImplementation?(snapshot?.operations||[]).find(row=>row.document&&relationshipIds(selectedImplementation.parents).includes(row.document.id))?.document:null;const selectedModels=selectedImplementation?.modelSelection?.models||[];const implementationBindings=(selectedImplementation?.bindings||{}) as Record<string,unknown>;const selectedPrompts=Array.isArray(implementationBindings.prompts)?implementationBindings.prompts as string[]:[];const selectedPromptProfiles=Array.isArray(implementationBindings.promptProfiles)?implementationBindings.promptProfiles as string[]:implementationBindings.promptProfile?[String(implementationBindings.promptProfile)]:[];const variants=abstract?(children.get(abstract.id)||[]):[];const directRoute=abstract?.implementation&&variants.length===0?abstract.implementation:null;
  const patchAbstract=(patch:Partial<OperationDef>)=>{if(!abstract)return;updateSource(doc.key,JSON.stringify({...abstract,...patch},null,2))};
  const setDefaultImplementation=(id:string)=>{if(!abstract)return;const children=abstract.children?.length?abstract.children:variants.map(row=>row.document?.id).filter(Boolean) as string[];patchAbstract({preferredChild:id||undefined,children})};
  const patchImpl=(patch:Partial<OperationImplementationDef>)=>{if(!selectedImplementation)return;updateSource(doc.key,JSON.stringify({...selectedImplementation,...patch},null,2))};
  const toggleModel=(id:string)=>{if(!selectedImplementation)return;const models=selectedModels.includes(id)?selectedModels.filter(x=>x!==id):[...selectedModels,id];patchImpl({modelSelection:{models,strategy:selectedImplementation.modelSelection?.strategy||"single"}})};
  const updatePrompts=(ids:string[])=>{if(!selectedImplementation)return;patchImpl({bindings:{...(selectedImplementation.bindings||{}),prompts:ids,separator:selectedImplementation.bindings?.separator||"\n\n"}})};
  const togglePrompt=(id:string)=>updatePrompts(selectedPrompts.includes(id)?selectedPrompts.filter(x=>x!==id):[...selectedPrompts,id]);
  const togglePromptProfile=(id:string)=>{if(!selectedImplementation)return;const promptProfiles=selectedPromptProfiles.includes(id)?selectedPromptProfiles.filter(x=>x!==id):[...selectedPromptProfiles,id];const bindings:Record<string,unknown>={...(selectedImplementation.bindings||{}),promptProfiles};delete bindings.promptProfile;patchImpl({bindings})};
  const movePrompt=(index:number,delta:number)=>{const next=[...selectedPrompts],to=index+delta;if(to<0||to>=next.length)return;[next[index],next[to]]=[next[to],next[index]];updatePrompts(next)};
  return <section className={`operation-editor-document ${secondary?"secondary":"primary"}`} key={doc.key}>
   <div className="operation-editor-toolbar"><div><span>{isImplementation?"OPERATION IMPLEMENTATION":"ABSTRACT OPERATION"}{doc.dirty?" · UNSAVED":""}</span><h2>{document?.label||document?.id||displayResourcePath(doc.record.path)}</h2><small>{doc.record.source} · {displayResourcePath(doc.record.path)}</small></div><div className="operation-editor-actions">{document&&<button className={document.enabled===false?"enable-resource":"disable-resource"} onClick={()=>updateSource(doc.key,JSON.stringify({...document,enabled:document.enabled===false},null,2))}>{document.enabled===false?"Enable Resource":"Disable Resource"}</button>}{!secondary&&<button onClick={chooseComparison}>{compareKey?"Single pane":"Split view"}</button>}<button className="primary" onClick={()=>saveDoc(doc)} disabled={busy||!document}>Save</button></div></div>
   <div className="operation-editor-scroll">
    {!document&&<div className="demo-notice"><b>Invalid resource</b><span>Fix the source before saving this resource.</span></div>}
    {abstract&&<><div className="operation-abstract-summary"><div><span>ROLE</span><b>{abstract.role||"abstract_stage"}</b></div><div><span>DEFAULT IMPLEMENTATION</span><select value={directRoute?abstract.id:abstract.preferredChild||""} disabled={Boolean(directRoute)} onChange={e=>setDefaultImplementation(e.target.value)}>{directRoute?<option value={abstract.id}>Direct — {directRoute}</option>:<option value="">planner-selected</option>}{variants.map(row=>{const impl=row.document!;const language=impl.implementation.startsWith("python")?"Python":impl.implementation.startsWith("prolog")?"Prolog":impl.implementation.startsWith("metta")?"MeTTa":impl.implementation.startsWith("llm")?"LLM":"Implementation";return <option key={impl.id} value={impl.id}>{language} — {impl.label||impl.id}</option>})}</select></div><div><span>INPUTS</span><code>{Object.keys(abstract.inputs||{}).join(", ")||"—"}</code></div><div><span>OUTPUTS</span><code>{Object.keys(abstract.outputs||{}).join(", ")||"—"}</code></div></div><OperationPlayground workspaceId={workspaceId} operation={abstract} variants={variants.filter(row=>row.document).map(row=>row.document!)} models={(snapshot?.models||[]).filter(row=>row.document).map(row=>({id:row.document!.id,label:row.document!.label,enabled:row.document!.enabled}))} onDefaultImplementationChange={setDefaultImplementation}/></>}
    {selectedImplementation&&<div className="implementation-summary"><div><span>ROUTE</span><b>{selectedImplementation.implementation}</b></div><div><span>IMPLEMENTS</span><b>{relationshipIds(selectedImplementation.parents).join(", ")}</b></div>{selectedImplementation.python&&<div className="wide"><span>PYTHON SOURCE</span><code>{String(selectedImplementation.python.module||selectedImplementation.python.file||"configured source")}{selectedImplementation.python.className?` · ${String(selectedImplementation.python.className)}`:""}{selectedImplementation.python.callable?` :: ${String(selectedImplementation.python.callable)}`:""}</code></div>}{selectedImplementation.prolog&&<div className="wide"><span>SWI-PROLOG SOURCE</span><code>{String(selectedImplementation.prolog.predicate||"predicate")} / {String(selectedImplementation.prolog.arity||"?")}</code></div>}{selectedImplementation.metta&&<div className="wide"><span>METTA SOURCE</span><code>{jsonValueToMetta(selectedImplementation.metta)}</code></div>}</div>}
    {selectedImplementation&&parentOperation&&<OperationPlayground key={`${parentOperation.id}:${selectedImplementation.id}`} workspaceId={workspaceId} operation={parentOperation} variants={[selectedImplementation]} models={(snapshot?.models||[]).filter(row=>row.document).map(row=>({id:row.document!.id,label:row.document!.label,enabled:row.document!.enabled}))}/>}
    {selectedImplementation?.implementation.startsWith("llm")&&promptProfiles.length>0&&<div className="operation-llm-config"><div className="llm-subhead"><div><span>PROMPT PROFILES</span><b>Reusable ordered prompt compositions, independent of the selected model or preset</b></div></div><div className="operation-model-list compact">{promptProfiles.map(row=>{const item=row.document!,checked=selectedPromptProfiles.includes(item.id);return <label className={`operation-model-option ${checked?"selected":""}`} key={item.id}><input type="checkbox" checked={checked} onChange={()=>togglePromptProfile(item.id)}/><span><b>{item.label||item.id}</b><small>{item.prompts.length} prompts · {item.description||row.path}</small></span></label>})}</div></div>}
    {selectedImplementation?.implementation.startsWith("llm")&&<div className="operation-llm-config"><div className="llm-subhead"><div><span>MODEL / PRESET DISPATCH</span><b>Models and reusable invocation presets allowed for this implementation</b></div></div><div className="operation-model-list compact">{enabledModels.map(row=>{const item=row.document!,checked=selectedModels.includes(item.id);return <label className={`operation-model-option ${checked?"selected":""}`} key={item.id}><input type="checkbox" checked={checked} onChange={()=>toggleModel(item.id)}/><span><b>{item.label||item.id}</b><small>{item.kind} · {row.resolved?.model||item.model||"inherited model"}</small></span></label>})}</div><div className="llm-subhead"><div><span>PROMPT COMPOSITION</span><b>Ordered prompts used by this implementation</b></div></div><div className="operation-model-list compact">{prompts.map(row=>{const item=row.document!,checked=selectedPrompts.includes(item.id),index=selectedPrompts.indexOf(item.id);return <div className={`operation-model-option ${checked?"selected":""}`} key={item.id}><input type="checkbox" checked={checked} onChange={()=>togglePrompt(item.id)}/><span><b>{item.label||item.id}</b><small>{item.description||row.path}</small></span>{checked&&<em><button onClick={()=>movePrompt(index,-1)} disabled={index===0}>↑</button> {index+1} <button onClick={()=>movePrompt(index,1)} disabled={index===selectedPrompts.length-1}>↓</button></em>}</div>})}</div></div>}
    <ResourceSourceEditor value={doc.source} onChange={value=>updateSource(doc.key,value)} label="Edit the selected item directly" showEnablement={false} />
   </div>
  </section>};

 if(!snapshot)return <section className="resource-view"><div className="studio-empty">Loading operation library…</div></section>;
 const toggleOperation=(id:string)=>setCollapsedOperations(current=>{const next=new Set(current);if(next.has(id))next.delete(id);else next.add(id);return next});
 const visibleOperations=(snapshot.operations||[]).filter(row=>row.document&&(!sourceLanguage||implementations.some(impl=>relationshipIds(impl.document?.parents).includes(row.document!.id))||row.document.implementation?.startsWith(sourceLanguage)));
 const operationIds=visibleOperations.flatMap(operation=>operation.document?[operation.document.id]:[]);
 const commandCategories=(action:"collapse"|"expand")=>setCategoryCommand(current=>({action,revision:(current?.revision||0)+1}));
 const commandOperations=(action:"collapse"|"expand",ids=operationIds)=>setCollapsedOperations(current=>{const next=new Set(current);for(const id of ids)action==="collapse"?next.add(id):next.delete(id);return next});
 const commandBranches=(action:"collapse"|"expand",target:string)=>{if(target==="all"){commandCategories(action);commandOperations(action);return}if(target==="categories"){commandCategories(action);return}const rows=(snapshot.operations||[]).filter(row=>{const item=row.document;if(!item)return false;const variants=children.get(item.id)||[];if(target==="top-operation")return true;if(target==="childless-operation")return variants.length===0;if(target==="enabled")return resolveResourceEnablement(item).enabled;if(target==="disabled")return !resolveResourceEnablement(item).enabled;if(target==="search")return JSON.stringify(item).toLowerCase().includes(treeFilter.trim().toLowerCase());return false});commandOperations(action,rows.flatMap(row=>row.document?[row.document.id]:[]))};
 const categorizedOperations=(snapshot.operations||[]).flatMap(operation=>{const item=operation.document;if(!item)return[];const variants=children.get(item.id)||[];const parentEnablement=resolveResourceEnablement(item);const categories=[...new Set([...categoryPaths(item.categories),...variants.flatMap(variant=>categoryPaths(variant.document?.categories))])];return [{id:item.id,categories,searchValue:item,render:(appearanceKey:string)=>{const selectedOperation=active?.record.document?.id===item.id;const branchCollapsed=collapsedOperations.has(item.id);const categoryPath=appearanceCategoryPath(appearanceKey,item.id);const operationBelongsHere=categoryPath!==null&&categoryPaths(item.categories).includes(categoryPath);const visibleVariants=categoryPath&&!operationBelongsHere?variants.filter(variant=>categoryPaths(variant.document?.categories).includes(categoryPath)):variants;return <div className={`operation-tree-group ${branchCollapsed?"branch-collapsed":""}`} key={appearanceKey} data-tree-search={JSON.stringify(item)}>
  <div className="inheritance-row"><button className={`operation-tree-row operation-parent ${enablementClass(parentEnablement)} ${selectedOperation?"selected":""}`} onClick={()=>open(operation as RecordFile<OperationResource>)}><span className="operation-kind-badge">OPERATION</span><span><b>{item.label||item.id}</b><small>{item.description||item.id}</small></span><em>{visibleVariants.length} variants <ResourceEnablementBadge state={parentEnablement}/></em></button>{visibleVariants.length>0&&<button type="button" className="tree-branch-toggle" title={branchCollapsed?"Unhide Variants":"Hide Variants"} aria-label={`${branchCollapsed?"Unhide":"Hide"} Variants for ${item.label||item.id}`} aria-expanded={!branchCollapsed} onClick={()=>toggleOperation(item.id)}><span aria-hidden="true">{branchCollapsed?"›":"⌄"}</span><b>{branchCollapsed?"Unhide Variants":"Hide Variants"}</b></button>}</div>
  <div className="operation-tree-children">{visibleVariants.map(variant=>{const impl=variant.document!;const implEnablement=resolveResourceEnablement(impl,parentEnablement);const selectedImpl=active?.record.document?.id===impl.id;const language=impl.implementation.startsWith("python")?"PYTHON":impl.implementation.startsWith("prolog")?"PROLOG":impl.implementation.startsWith("metta")?"METTA":impl.implementation.startsWith("llm")?"LLM":"IMPL";return <button className={`operation-tree-row operation-child ${enablementClass(implEnablement)} ${selectedImpl?"selected":""}`} key={impl.id} data-tree-search={JSON.stringify(impl)} onClick={()=>open(variant as RecordFile<OperationResource>)}><span className={`operation-kind-badge ${language.toLowerCase()}`}>{language}</span><span><b>{impl.label||impl.id}</b><small>{impl.implementation}</small></span><em>{item.preferredChild===impl.id?"default ":""}<ResourceEnablementBadge state={implEnablement}/></em></button>})}</div>
 </div>}}]});
 return <section className="resource-view operation-hierarchy-page">
  <div className="resource-heading"><div><span>{sourceLanguage?`${sourceLanguage.toUpperCase()} SOURCE LIBRARY`:"OPERATION CONTRACT SYSTEM"}</span><h1>{sourceLanguage?`${sourceLanguage==="metta"?"MeTTa":sourceLanguage[0].toUpperCase()+sourceLanguage.slice(1)} implementation source`:"Operations & implementations"}</h1><p>{sourceLanguage?`Operations implemented through the ${sourceLanguage} backend. Select an implementation to edit its maintained source and execution binding.`:<>Every resource has <code>kind operation</code>. An Operation with a same-kind parent is a concrete implementation alternative; roots are abstract contracts.</>}</p></div></div>
  {error&&<div className="demo-notice"><b>Operation editor error</b><span>{error}</span></div>}
  <div className={`operation-hierarchy-layout operation-hierarchy ${navigatorCollapsed?"navigator-collapsed":"navigator-expanded"}`}>
   <div className="operation-tree-pane artifact-navigator operation-category-enabled">
    <div className="artifact-navigator-content categorized-operation-content" ref={treeRef}><CategorizedArtifactTree items={categorizedOperations} onlyCategories={false} categoryCommand={categoryCommand} workspaceId={workspaceId} categoryTree="operations"/></div>
    <div className="artifact-navigator-toolbar"><span>OPERATIONS</span><div className="artifact-navigator-actions"><label className="artifact-tree-filter"><span>Filter tree</span><input type="search" value={treeFilter} onChange={event=>setTreeFilter(event.target.value)} placeholder="Filter tree…" /></label><div className="tree-repeat-permanent"><RepeatSwitch value={visibilityRules.repeats} onChange={repeats=>setVisibilityRules({...visibilityRules,repeats})}/></div><button type="button" aria-label="Expand All" onClick={()=>commandBranches("expand","all")}><b>Expand All</b></button><button type="button" aria-label="Collapse All" onClick={()=>commandBranches("collapse","all")}><b>Collapse All</b></button><button type="button" aria-label="Tree View Controls" aria-expanded={viewControlsOpen} aria-pressed={viewControlsOpen} onClick={()=>setViewControlsOpen(value=>!value)}><b>{viewControlsOpen?"Hide View":"Show View"}</b></button><button type="button" aria-label={navigatorCollapsed?"Expand operations hierarchy":"Collapse operations hierarchy"} aria-expanded={!navigatorCollapsed} onClick={()=>setNavigatorCollapsed(value=>!value)}>{navigatorCollapsed?"›":"‹"}<b>{navigatorCollapsed?"":"Pane"}</b></button></div></div>
    {viewControlsOpen&&<TreeViewControls kinds={treeKinds} rules={visibilityRules} onChange={setVisibilityRules} showParents={showParents} onShowParentsChange={setShowParents} onBranchAction={commandBranches}/>}
   </div>
   <div className="operation-editor-workspace">
    <div className="operation-document-tabs">{openDocs.map(doc=><div className={`operation-document-tab ${doc.key===activeKey?"active":""}`} key={doc.key}><button onClick={()=>setActiveKey(doc.key)}><span>{relationshipIds(doc.record.document?.parents).length?"IMPL":"OPERATION"}</span><b>{doc.record.document?.label||doc.record.document?.id||doc.record.path}</b>{doc.dirty&&<i>●</i>}</button><button className="close" onClick={()=>close(doc.key)}>×</button></div>)}</div>
    <div className={`operation-editor-panes ${comparison?"split":"single"}`}>
      {active?renderEditor(active):<div className="studio-empty">Select a operation or implementation.</div>}
      {comparison&&renderEditor(comparison,true)}
    </div>
   </div>
  </div>
 </section>;
}
