import { useEffect, useMemo, useState } from "react";
import { ArtifactTreeBranch } from "./ArtifactTreeBranch";
import { HierarchyResourceEditor } from "./HierarchyResourceEditor";
import "../styles/operation_editor.css";

type Policy = { kind:string; id:string; label?:string; description?:string; enabled?:boolean; implements?:string[]; variants?:string[]; variantSelection?:{default?:string;variants?:string[]}; [key:string]:unknown };
type RecordFile = { path:string; source?:"shared"|"workspace"; workspaceId?:string; document?:Policy; error?:string };
type Payload = { resources:RecordFile[]; hierarchy:{roots:RecordFile[];variants:RecordFile[];variantsByParent:Record<string,RecordFile[]>} };
type OpenDocument = { key:string; record:RecordFile; source:string; dirty:boolean };
const slug=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"")||"policy";
const recordKey=(record:RecordFile)=>`${record.workspaceId||record.source||"resource"}:${record.path}:${record.document?.id||"unknown"}`;
async function request(path:string,init?:RequestInit){const response=await fetch(path,{headers:{"Content-Type":"application/json",...(init?.headers||{})},...init});const body=await response.json();if(!response.ok)throw new Error(body.error||body.detail||response.statusText);return body;}

export function PolicyLibraryEditor({workspaceId}:{workspaceId:string}){
 const[payload,setPayload]=useState<Payload|null>(null),[openDocs,setOpenDocs]=useState<OpenDocument[]>([]),[activeKey,setActiveKey]=useState<string|null>(null),[compareKey,setCompareKey]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const load=async()=>{const next=await request(`/api/workspaces/${encodeURIComponent(workspaceId)}/policies`) as Payload;setPayload(next);return next};
 useEffect(()=>{setOpenDocs([]);setActiveKey(null);setCompareKey(null);void load().catch(reason=>setError(String(reason)))},[workspaceId]);
 const roots=useMemo(()=>[...(payload?.hierarchy.roots||[])].sort((a,b)=>String(a.document?.label||a.path).localeCompare(String(b.document?.label||b.path))),[payload]);
 const children=payload?.hierarchy.variantsByParent||{};
 const open=(record:RecordFile)=>{const key=recordKey(record);setOpenDocs(current=>current.some(doc=>doc.key===key)?current:[...current,{key,record,source:record.document?JSON.stringify(record.document,null,2):"",dirty:false}]);setActiveKey(key)};
 useEffect(()=>{if(payload&&openDocs.length===0&&roots[0])open(roots[0])},[payload,roots]);
 const active=openDocs.find(doc=>doc.key===activeKey)||null;
 const close=(key:string)=>setOpenDocs(current=>{const index=current.findIndex(doc=>doc.key===key),next=current.filter(doc=>doc.key!==key);if(activeKey===key)setActiveKey(next[Math.max(0,index-1)]?.key||next[0]?.key||null);if(compareKey===key)setCompareKey(null);return next});
 const update=(key:string,source:string)=>setOpenDocs(current=>current.map(doc=>doc.key===key?{...doc,source,dirty:true}:doc));
 const compare=()=>{if(compareKey){setCompareKey(null);return}const other=[...openDocs].reverse().find(doc=>doc.key!==activeKey);if(other)setCompareKey(other.key)};
 const createPolicy=()=>open({path:"policies/new_policy.model_policy.json",source:workspaceId==="shared"?"shared":"workspace",workspaceId,document:{kind:"model_policy",id:"new_policy",label:"New Policy",description:"Filesystem-backed policy specification.",enabled:true,variantSelection:{variants:[]}}});
 const save=(doc:OpenDocument)=>{setBusy(true);setError(null);void(async()=>{try{const document=JSON.parse(doc.source) as Policy;if(!document.id||!document.kind)throw new Error("Policy requires id and kind");const path=workspaceId==="shared"||doc.record.source==="workspace"?doc.record.path:`policies/${slug(document.id)}.${document.kind}.json`;await request(`/api/workspaces/${encodeURIComponent(workspaceId)}/file`,{method:"PUT",body:JSON.stringify({path,content:JSON.stringify(document,null,2)})});const next=await load();const saved=next.resources.find(row=>row.document?.id===document.id);if(saved){const key=recordKey(saved);setOpenDocs(current=>current.map(item=>item.key===doc.key?{key,record:saved,source:JSON.stringify(saved.document,null,2),dirty:false}:item));setActiveKey(key)}}catch(reason){setError(String(reason))}finally{setBusy(false)}})()};
 const render=(doc:OpenDocument,secondary=false)=>{let item:Policy|null=null;try{item=JSON.parse(doc.source)}catch{}return <section className={`operation-editor-document ${secondary?"secondary":"primary"}`}><div className="operation-editor-toolbar"><div><span>{item?.kind?.toUpperCase()||"POLICY"}{doc.dirty?" · UNSAVED":""}</span><h2>{item?.label||item?.id||doc.record.path}</h2><small>{doc.record.source} · {doc.record.path}</small></div><div className="operation-editor-actions">{!secondary&&<button onClick={compare}>{compareKey?"Single pane":"Split view"}</button>}<button className="primary" disabled={busy||!item} onClick={()=>save(doc)}>Save</button></div></div><div className="operation-editor-scroll">{item&&<div className="operation-abstract-summary"><div><span>ENABLED</span><label><input type="checkbox" checked={item.enabled!==false} onChange={event=>update(doc.key,JSON.stringify({...item,enabled:event.target.checked},null,2))}/>{item.enabled!==false?" enabled":" disabled"}</label></div><div><span>KIND</span><code>{item.kind}</code></div><div><span>ID</span><code>{item.id}</code></div><div><span>SOURCE</span><code>{doc.record.source}</code></div></div>}<textarea className="raw-json-editor operation-visible-editor" value={doc.source} onChange={event=>update(doc.key,event.target.value)}/></div></section>};
 if(!payload)return <section className="resource-view"><div className="studio-empty">Loading policy library…</div></section>;
 const leftPane=<>{roots.map(record=>{const item=record.document;if(!item)return null;const variants=children[item.id]||[];return <ArtifactTreeBranch key={item.id} label={item.label||item.id} searchValue={item} header={<button className={`operation-tree-row operation-parent ${active?.record.document?.id===item.id?"selected":""}`} onClick={()=>open(record)}><span className="operation-kind-badge">{item.kind.replace(/_/g," ").toUpperCase()}</span><span><b>{item.label||item.id}</b><small>{item.description||item.id}</small></span><em>{item.enabled===false?"disabled":variants.length?`${variants.length} variants`:"enabled"}</em></button>}>{variants.length?variants.map(row=>{const child=row.document!;return <button className={`operation-tree-row operation-child ${active?.record.document?.id===child.id?"selected":""}`} data-tree-search={JSON.stringify(child)} key={child.id} onClick={()=>open(row)}><span className="operation-kind-badge llm">VARIANT</span><span><b>{child.label||child.id}</b><small>{child.description||child.id}</small></span><em>{child.enabled===false?"disabled":"enabled"}</em></button>}):undefined}</ArtifactTreeBranch>})}</>;
 const tabs=openDocs.map(doc=>({key:doc.key,kind:doc.record.document?.kind?.toUpperCase()||"POLICY",label:doc.record.document?.label||doc.record.document?.id||doc.record.path,dirty:doc.dirty}));
 return <HierarchyResourceEditor eyebrow="POLICY DESIGN" title="Policies & variants" description="Editable shared and workspace policy JSON resources. SYSTEM Model Policy will inspect their effective runtime resolution." headerActions={<button onClick={createPolicy}>+ Policy</button>} error={error} onDismissError={()=>setError(null)} leftPane={leftPane} tabs={tabs} activeKey={activeKey} compareKey={compareKey} onActivate={setActiveKey} onClose={close} renderEditor={(key,secondary)=>{const doc=openDocs.find(item=>item.key===key);return doc?render(doc,secondary):null}} emptyEditor={<div className="studio-empty">Select a policy resource.</div>}/>;
}
