import {useEffect,useMemo,useState} from "react";
import {HierarchyResourceEditor} from "./HierarchyResourceEditor";
import {ArtifactTreeBranch} from "./ArtifactTreeBranch";
import {relationshipIds} from "./resourceRelationships";
import "../styles/operation_editor.css";

type Source="shared"|"workspace";
type RecordFile<T>={path:string;source?:Source;workspaceId?:string;document?:T;error?:string};
type PromptDef={kind:"prompt";id:string;label?:string;description?:string;inputs?:Record<string,string>;outputs?:Record<string,string>;text?:string|string[];variables?:string[];children?:string[];preferredChild?:string;metadata?:Record<string,unknown>};
type PromptImplementationDef={kind:"prompt_implementation";id:string;parents:string[];label?:string;description?:string;version?:number;targets?:string[];language?:string;text:string|string[];metadata?:Record<string,unknown>};
type PromptResource=PromptDef|PromptImplementationDef;
type PromptHierarchy={prompts:RecordFile<PromptDef>[];promptImplementations:RecordFile<PromptImplementationDef>[];implementationsByPrompt:Record<string,RecordFile<PromptImplementationDef>[]>};
type PromptPayload={workspace:{id:string;label:string;root:string};prompts:RecordFile<PromptDef>[];promptLibrary?:{hierarchy?:PromptHierarchy}};
type OpenDocument={key:string;record:RecordFile<PromptResource>;source:string;dirty:boolean};

const slug=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"")||"prompt";
const recordKey=(record:RecordFile<PromptResource>)=>`${record.workspaceId||record.source||"resource"}:${record.path}:${record.document?.id||"unknown"}`;
async function request(path:string,init?:RequestInit){const response=await fetch(path,{headers:{"Content-Type":"application/json",...(init?.headers||{})},...init});const payload=await response.json();if(!response.ok)throw new Error(payload.error||payload.detail||response.statusText);return payload;}

export function PromptLibraryEditor({workspaceId}:{workspaceId:string}){
 const[payload,setPayload]=useState<PromptPayload|null>(null),[openDocs,setOpenDocs]=useState<OpenDocument[]>([]),[activeKey,setActiveKey]=useState<string|null>(null),[compareKey,setCompareKey]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const load=async()=>{const next=await request(`/api/workspaces/${encodeURIComponent(workspaceId)}/prompts`) as PromptPayload;setPayload(next);return next};
 useEffect(()=>{setOpenDocs([]);setActiveKey(null);setCompareKey(null);void load().catch(reason=>setError(String(reason)))},[workspaceId]);
 const hierarchy=payload?.promptLibrary?.hierarchy;
 const prompts=hierarchy?.prompts||payload?.prompts||[];
 const implementations=hierarchy?.promptImplementations||[];
 const children=hierarchy?.implementationsByPrompt||{};
 const featuredPrompts=useMemo(()=>[...prompts].sort((a,b)=>{const aid=a.document?.id||"",bid=b.document?.id||"";const ac=(children[aid]||[]).length,bc=(children[bid]||[]).length;if(aid==="titlecase_received_text"&&bid!=="titlecase_received_text")return -1;if(bid==="titlecase_received_text"&&aid!=="titlecase_received_text")return 1;if(bc!==ac)return bc-ac;return String(a.document?.label||aid||a.path).localeCompare(String(b.document?.label||bid||b.path))}),[prompts,children]);
 const open=(record:RecordFile<PromptResource>)=>{const key=recordKey(record);setOpenDocs(current=>current.some(doc=>doc.key===key)?current:[...current,{key,record,source:record.document?JSON.stringify(record.document,null,2):"",dirty:false}]);setActiveKey(key)};
 useEffect(()=>{if(payload&&openDocs.length===0&&featuredPrompts[0])open(featuredPrompts[0] as RecordFile<PromptResource>)},[payload,featuredPrompts]);
 const updateSource=(key:string,source:string)=>setOpenDocs(current=>current.map(doc=>doc.key===key?{...doc,source,dirty:true}:doc));
 const active=openDocs.find(doc=>doc.key===activeKey)||null;
 const close=(key:string)=>{setOpenDocs(current=>{const index=current.findIndex(doc=>doc.key===key);const next=current.filter(doc=>doc.key!==key);if(activeKey===key)setActiveKey(next[Math.max(0,index-1)]?.key||next[0]?.key||null);if(compareKey===key)setCompareKey(null);return next})};
 const chooseComparison=()=>{if(compareKey){setCompareKey(null);return}const other=[...openDocs].reverse().find(doc=>doc.key!==activeKey);if(other)setCompareKey(other.key)};
 const perform=async(work:()=>Promise<void>)=>{setBusy(true);setError(null);try{await work()}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}};
 const newPrompt=()=>{const id="new_prompt";const doc:PromptDef={kind:"prompt",id,label:"New Prompt",description:"Abstract prompt contract.",inputs:{text:"text"},outputs:{text:"text"},children:[`${id}.default`],preferredChild:`${id}.default`};open({path:`prompts/${id}.prompt.json`,source:workspaceId==="shared"?"shared":"workspace",workspaceId,document:doc})};
 const newImplementation=(parent:PromptDef)=>{const id=`${parent.id}.alternative`;const doc:PromptImplementationDef={kind:"prompt_implementation",id,parents:[parent.id],label:`${parent.label||parent.id} — Alternative`,version:1,targets:["generic-chat"],text:["Implement the abstract prompt contract.","Return only the requested output."]};open({path:`prompts/${slug(id)}.prompt_implementation.json`,source:workspaceId==="shared"?"shared":"workspace",workspaceId,document:doc})};
 const saveDoc=(doc:OpenDocument)=>perform(async()=>{let document:PromptResource;try{document=JSON.parse(doc.source) as PromptResource}catch{throw new Error("Prompt resource JSON is invalid")};if(!document.id||!["prompt","prompt_implementation"].includes(document.kind))throw new Error("Prompt resource requires id and a valid kind");if(document.kind==="prompt_implementation"&&!relationshipIds(document.parents).length)throw new Error("Prompt implementation requires parents");const original=doc.record.path;const path=workspaceId==="shared"||doc.record.source==="workspace"?original:`prompts/${slug(document.id)}.${document.kind}.json`;await request(`/api/workspaces/${encodeURIComponent(workspaceId)}/file`,{method:"PUT",body:JSON.stringify({path,content:JSON.stringify(document,null,2)})});const next=await load();const h=next.promptLibrary?.hierarchy;const pool:RecordFile<PromptResource>[]=[...(h?.prompts||next.prompts||[]),...(h?.promptImplementations||[])];const saved=pool.find(row=>row.document?.id===document.id);if(saved){const newKey=recordKey(saved);setOpenDocs(current=>current.map(item=>item.key===doc.key?{key:newKey,record:saved,source:JSON.stringify(saved.document,null,2),dirty:false}:item));if(activeKey===doc.key)setActiveKey(newKey);if(compareKey===doc.key)setCompareKey(newKey)}});

 const renderEditor=(doc:OpenDocument,secondary=false)=>{let document:PromptResource|null=null;try{document=doc.source?JSON.parse(doc.source) as PromptResource:null}catch{document=null}const parent=document?.kind==="prompt"?document:null;const impl=document?.kind==="prompt_implementation"?document:null;const variants=parent?(children[parent.id]||[]):[];
  const patchParent=(patch:Partial<PromptDef>)=>{if(!parent)return;updateSource(doc.key,JSON.stringify({...parent,...patch},null,2))};
  const setPreferred=(id:string)=>{if(!parent)return;const children=parent.children?.length?parent.children:variants.map(row=>row.document?.id).filter(Boolean) as string[];patchParent({preferredChild:id||undefined,children})};
  return <section className={`operation-editor-document ${secondary?"secondary":"primary"}`} key={doc.key}><div className="operation-editor-toolbar"><div><span>{parent?"ABSTRACT PROMPT":"PROMPT IMPLEMENTATION"}{doc.dirty?" · UNSAVED":""}</span><h2>{document?.label||document?.id||doc.record.path}</h2><small>{doc.record.source} · {doc.record.path}</small></div><div className="operation-editor-actions">{!secondary&&<button onClick={chooseComparison}>{compareKey?"Single pane":"Split view"}</button>}{parent&&<button onClick={()=>newImplementation(parent)}>+ Alternative</button>}<button className="primary" disabled={busy||!document} onClick={()=>saveDoc(doc)}>Save</button></div></div><div className="operation-editor-scroll">{!document&&<div className="demo-notice"><b>Invalid JSON</b><span>Fix the JSON before saving.</span></div>}{parent&&<><div className="operation-abstract-summary"><div><span>PREFERRED ALTERNATIVE</span><select value={parent.preferredChild||""} onChange={e=>setPreferred(e.target.value)}><option value="">planner-selected</option>{variants.map(row=><option key={row.document?.id} value={row.document?.id}>{row.document?.label||row.document?.id}</option>)}</select></div><div><span>ALTERNATIVES</span><code>{variants.length}</code></div><div><span>INPUTS</span><code>{Object.keys(parent.inputs||{}).join(", ")||"—"}</code></div><div><span>OUTPUTS</span><code>{Object.keys(parent.outputs||{}).join(", ")||"—"}</code></div></div><div className="operation-model-list compact">{variants.map(row=>{const child=row.document!;const preferred=parent.preferredChild===child.id;return <button className={`operation-model-option ${preferred?"selected":""}`} key={child.id} onClick={()=>open(row as RecordFile<PromptResource>)}><span><b>{child.label||child.id}</b><small>{(child.targets||[]).join(", ")||"generic"} · v{child.version||1}</small></span><em>{preferred?"preferred":"alternative"}</em></button>})}</div></>}{impl&&<div className="implementation-summary"><div><span>IMPLEMENTS</span><b>{relationshipIds(impl.parents).join(", ")}</b></div><div><span>TARGETS</span><b>{(impl.targets||[]).join(", ")||"generic"}</b></div><div><span>VERSION</span><b>{impl.version||1}</b></div></div>}<div className="operation-json-block"><div className="llm-subhead"><div><span>RESOURCE JSON</span><b>Edit the selected prompt asset directly</b></div></div><textarea className="raw-json-editor operation-visible-editor" value={doc.source} onChange={e=>updateSource(doc.key,e.target.value)}/></div></div></section>};

 if(!payload)return <section className="resource-view"><div className="studio-empty">Loading prompt library…</div></section>;
 const leftPane=<>{featuredPrompts.map(prompt=>{const item=prompt.document;if(!item)return null;const variants=children[item.id]||[];return <ArtifactTreeBranch key={item.id} label={item.label||item.id} searchValue={item} header={<div className="inheritance-row"><button className={`operation-tree-row operation-parent ${active?.record.document?.id===item.id?"selected":""}`} onClick={()=>open(prompt as RecordFile<PromptResource>)}><span className="operation-kind-badge">PROMPT</span><span><b>{item.label||item.id}</b><small>{item.description||item.id}</small></span><em>{variants.length} alternatives</em></button><button className="hier-mini" onClick={()=>newImplementation(item)}>+ alt</button></div>}>{variants.length?variants.map(variant=>{const child=variant.document!;const preferred=item.preferredChild===child.id;return <button className={`operation-tree-row operation-child ${active?.record.document?.id===child.id?"selected":""}`} key={child.id} data-tree-search={JSON.stringify(child)} onClick={()=>open(variant as RecordFile<PromptResource>)}><span className="operation-kind-badge llm">ALT</span><span><b>{child.label||child.id}</b><small>{(child.targets||[]).join(", ")||"generic"} · v{child.version||1}</small></span><em>{preferred?"preferred":""}</em></button>}):undefined}</ArtifactTreeBranch>})}</>;
 const tabs=openDocs.map(doc=>({key:doc.key,kind:doc.record.document?.kind==="prompt"?"PROMPT":"ALT",label:doc.record.document?.label||doc.record.document?.id||doc.record.path,dirty:doc.dirty}));
 const featured=featuredPrompts[0]?.document;const featuredChildren=featured?(children[featured.id]||[]):[];
 return <HierarchyResourceEditor eyebrow="PROMPT CONTRACT SYSTEM" title="Prompts & alternatives" description="Abstract prompts use the same hierarchy/tree/tab/split-view editor shell as Operations, Data, and Models." headerActions={<button onClick={newPrompt}>+ Abstract prompt</button>} notice={featured&&featuredChildren.length?<div className="demo-notice"><b>Alternatives visible now: {featured.label||featured.id}</b><span>{featuredChildren.map(row=>row.document?.label||row.document?.id).join(" · ")}</span></div>:undefined} error={error} onDismissError={()=>setError(null)} leftPane={leftPane} tabs={tabs} activeKey={activeKey} compareKey={compareKey} onActivate={setActiveKey} onClose={close} renderEditor={(key,secondary)=>{const doc=openDocs.find(item=>item.key===key);return doc?renderEditor(doc,secondary):null}} emptyEditor={<div className="studio-empty">Select a prompt or alternative.</div>} footer={<div className="demo-notice"><b>Hierarchy proof</b><span>{prompts.length} abstract prompt(s) · {implementations.length} alternatives.</span></div>}/>;
}
