import {useEffect,useMemo,useState} from "react";
import {jsonValueToMetta} from "../lib/mettaResourceCodec";
import {InvocationDebugTrace} from "./InvocationDebugTrace";
import {UniversalExecutionControls,type RunnerPopulationMode} from "./UniversalExecutionControls";
import {AutoGrowingTextarea} from "./AutoGrowingTextarea";
import "../styles/operation_playground.css";

type Resource={kind:string;id:string;label?:string;[key:string]:unknown};
type Operation={id:string;label?:string;description?:string};
type Model={id:string;label?:string;enabled?:boolean};
type RecordFile<T>={document?:T;resolved?:{enabled?:boolean}};
const defaults:Record<string,string[]>={semantic_datatype:["datatype_sample","datatype_validate","datatype_conversion_inspect","resource_validate"],representation_datatype:["datatype_conversion_inspect","datatype_sample","datatype_validate","resource_validate"],concrete_datatype:["datatype_conversion_inspect","datatype_sample","datatype_validate","resource_validate"],prompt:["prompt_render","prompt_compose","resource_validate"],prompt_profile:["prompt_compose","prompt_render","resource_validate"],goal:["goal_evaluate","goal_interpret","goal_check_satisfaction","resource_validate"],planning_strategy:["planning_strategy_preview","planning_strategy_generate","planned_workflow_validate","resource_validate"],atomspace:["atomspace_query","atomspace_assert","atomspace_retract","atomspace_inspect","resource_validate"],system:["system_inspect","system_check_readiness","resource_validate"],backend:["backend_inspect","backend_check_readiness","resource_validate"],data:["data_inspect","resource_validate"],artifact:["artifact_inspect","resource_validate"],model_policy:["policy_evaluate","policy_explain","resource_validate"],benchmark_policy:["policy_evaluate","policy_explain","resource_validate"],artifact_category:["category_preview","category_resolve_matches","resource_validate"]};
const defaultOperations=(kind:string)=>defaults[kind]||(kind.endsWith("_policy")?["policy_evaluate","policy_explain","resource_validate"]:["resource_validate"]);

async function request(path:string,init?:RequestInit){const response=await fetch(path,{cache:"no-store",headers:{"Content-Type":"application/json",...(init?.headers||{})},...init});const text=await response.text();let payload:any;try{payload=JSON.parse(text)}catch{throw new Error(text||response.statusText)}if(!response.ok){const detail=payload.detail||payload.error||response.statusText;throw new Error(typeof detail==="string"?detail:String(detail.message||JSON.stringify(detail)))}return payload}

export function ResourceExecutionPlayground({workspaceId,resource,operationIds}:{workspaceId:string;resource:Resource;operationIds?:string[]}){
 const preferredIds=operationIds||defaultOperations(resource.kind);
 const[operations,setOperations]=useState<Operation[]>([]),[models,setModels]=useState<Model[]>([]),[selectedOperation,setSelectedOperation]=useState(preferredIds[0]||"resource_validate"),[selectedModel,setSelectedModel]=useState(""),[input,setInput]=useState(()=>JSON.stringify(resource,null,2)),[running,setRunning]=useState(false),[populating,setPopulating]=useState<RunnerPopulationMode|null>(null),[message,setMessage]=useState<string|null>(null),[result,setResult]=useState<any>(null),[error,setError]=useState<string|null>(null),[debugPath,setDebugPath]=useState<string|null>(null),[debugLog,setDebugLog]=useState("");
 useEffect(()=>{setInput(JSON.stringify(resource,null,2));setSelectedOperation(preferredIds[0]||"resource_validate");setResult(null);setError(null);setDebugPath(null);setDebugLog("")},[resource.id,resource.kind]);
 useEffect(()=>{void Promise.all([request(`/workbench/workspaces/${encodeURIComponent(workspaceId)}/operations`),request(`/workbench/workspaces/${encodeURIComponent(workspaceId)}/snapshot`)]).then(([ops,snapshot])=>{const available=(ops.operations||[]).map((row:RecordFile<Operation>)=>row.document).filter(Boolean) as Operation[];const compatible=preferredIds.map(id=>available.find(item=>item.id===id)).filter(Boolean) as Operation[];setOperations(compatible);setSelectedOperation(current=>compatible.some(item=>item.id===current)?current:compatible[0]?.id||"");const modelRows=(snapshot.models||[]) as RecordFile<Model>[];const enabled=modelRows.filter(row=>row.document&&row.document.enabled!==false&&row.resolved?.enabled!==false).map(row=>row.document!) as Model[];setModels(enabled);setSelectedModel(current=>current||enabled[0]?.id||"")}).catch(reason=>setError(String(reason)))},[workspaceId,resource.kind]);
 const chosen=useMemo(()=>operations.find(item=>item.id===selectedOperation),[operations,selectedOperation]);
 const loadTrace=async(path:string)=>{setDebugPath(path);const payload=await request(`/workbench/workspaces/${encodeURIComponent(workspaceId)}/operations/debug-log?path=${encodeURIComponent(path)}`);setDebugLog(String(payload.content||""))};
 const run=async(operationId:string)=>{setRunning(true);setError(null);setResult(null);setDebugPath(null);setDebugLog("");try{const parsed=JSON.parse(input);const payload=await request(`/workbench/workspaces/${encodeURIComponent(workspaceId)}/operations/${encodeURIComponent(operationId)}/invoke`,{method:"POST",body:JSON.stringify({inputs:{resource:parsed},...(selectedModel?{modelSelection:{models:[selectedModel],strategy:"single"}}:{})})});setResult(payload);if(payload.debugLogPath)await loadTrace(payload.debugLogPath)}catch(reason){setError(reason instanceof Error?reason.message:String(reason))}finally{setRunning(false)}};
 const populate=async(mode:RunnerPopulationMode)=>{setPopulating(mode);setMessage(null);try{if(mode==="sample_input"){setInput(JSON.stringify(resource,null,2));setMessage("Restored the open filesystem resource as the sample input.");return}if(mode==="empty_null"){setInput("null");setMessage("Set the resource input to null so validation and error handling can be tested.");return}const responses=await Promise.allSettled([request(`/workbench/goal-runs?workspace_id=${encodeURIComponent(workspaceId)}&limit=100`),request(`/workbench/engine/runs?workspace_id=${encodeURIComponent(workspaceId)}&limit=100`)]);const candidates:Record<string,unknown>[]=[];const visit=(value:unknown)=>{if(!value||typeof value!=="object")return;if(!Array.isArray(value)&&("kind" in value||"id" in value))candidates.push(value as Record<string,unknown>);Object.values(value).forEach(visit)};responses.forEach(response=>{if(response.status==="fulfilled")visit(response.value)});const picked=mode==="random_outputs"?candidates[Math.floor(Math.random()*candidates.length)]:candidates[candidates.length-1];if(picked){setInput(JSON.stringify(picked,null,2));setMessage(`Loaded a ${mode==="random_outputs"?"random":"recent"} structured resource value from this workspace.`)}else setMessage("No compatible structured resource outputs were found; the current input was preserved.")}catch(reason){setError(String(reason))}finally{setPopulating(null)}};
 const defaultOperation=operations[0]?.id||"";
 const actions=<><button type="button" onClick={()=>void run(defaultOperation)} disabled={running||!defaultOperation}>{running?"Running…":"Run Default"}</button><button className="primary" type="button" onClick={()=>void run(selectedOperation)} disabled={running||!selectedOperation}>{running?"Running…":"▶ Run Selected"}</button></>;
 return <section className="operation-playground universal-resource-playground"><UniversalExecutionControls title="UNIVERSAL EXECUTION RUNNER" description="Run a compatible Operation against this filesystem resource" actions={actions} populating={populating} inputCount={1} onPopulate={populate}/><div className="operation-playground-grid"><label className="operation-playground-field"><span>OPERATION · ONE-OFF</span><select value={selectedOperation} onChange={event=>setSelectedOperation(event.target.value)}>{operations.map(item=><option key={item.id} value={item.id}>{item.label||item.id}</option>)}</select><small>{chosen?.description||"The resource kind supplies the preferred compatible operations."}</small></label><label className="operation-playground-field"><span>MODEL · ONE-OFF</span><select value={selectedModel} onChange={event=>setSelectedModel(event.target.value)}><option value="">No model / operation default</option>{models.map(item=><option key={item.id} value={item.id}>{item.label||item.id}</option>)}</select><small>Used when the selected Operation is model-backed; deterministic Operations ignore it.</small></label><label className="operation-playground-field" style={{gridColumn:"1/-1"}}><span>INPUT · resource <em>{resource.kind}</em></span><AutoGrowingTextarea className="tab-input-editor--opted-in" value={input} onChange={event=>setInput(event.target.value)} /></label></div>{message&&<div className="operation-population-status">{message}</div>}{error&&<div className="demo-notice"><b>Invocation failed</b><span>{error}</span></div>}{result&&<div className="operation-playground-result"><div><span>RESULT</span><b>{chosen?.label||selectedOperation}</b><small>{result.implementation?.route||"operation"} · {result.elapsedMs||0} ms</small></div><pre>{jsonValueToMetta(result.outputs||result)}</pre></div>}{debugPath&&<InvocationDebugTrace path={debugPath} content={debugLog}/>}<div className="operation-run-actions runner-actions-bottom">{actions}</div></section>;
}
