import {useEffect,useMemo,useState} from "react";

type Source="shared"|"workspace";type ModelStrategy="single"|"parallel"|"compare"|"fallback";
type RecordFile<T>={path:string;source?:Source;workspaceId?:string;document?:T;error?:string;resolved?:{enabled?:boolean;backendId?:string;defaults?:Record<string,unknown>;model?:string}};
type TaskDef={id:string;label?:string;description?:string;implementation:string;inputs?:Record<string,string>;outputs?:Record<string,string>;parameters?:Record<string,unknown>;modelSelection?:{models?:string[];strategy?:ModelStrategy};promptSelection?:{prompts?:string[];separator?:string}};
type ModelDef={kind:"model"|"profile";id:string;label?:string;inherits:string;model?:string;enabled?:boolean;defaults?:Record<string,unknown>};
type PromptDef={kind:"prompt";id:string;label?:string;description?:string;text:string|string[];variables?:string[]};
type Snapshot={workspace:{id:string;label:string;root:string};tasks:RecordFile<TaskDef>[];models:RecordFile<ModelDef>[];prompts:RecordFile<PromptDef>[]};
const slug=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_+|_+$/g,"")||"task";
async function request(path:string,init?:RequestInit){const r=await fetch(path,{headers:{"Content-Type":"application/json",...(init?.headers||{})},...init});const p=await r.json();if(!r.ok)throw new Error(p.error||p.detail||r.statusText);return p;}

export function TaskLibraryEditor({workspaceId}:{workspaceId:string}){
 const[snapshot,setSnapshot]=useState<Snapshot|null>(null),[selected,setSelected]=useState<RecordFile<TaskDef>|null>(null),[source,setSource]=useState(""),[target,setTarget]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const load=async()=>{const next=await request(`/api/workspaces/${encodeURIComponent(workspaceId)}/snapshot`) as Snapshot;setSnapshot(next);return next};useEffect(()=>{setSelected(null);void load().catch(r=>setError(String(r)))},[workspaceId]);
 const document=useMemo<TaskDef|null>(()=>{try{return source?JSON.parse(source) as TaskDef:null}catch{return null}},[source]);
 const enabledModels=(snapshot?.models||[]).filter(row=>row.document&&(row.resolved?.enabled??row.document.enabled!==false));const prompts=snapshot?.prompts||[];const selectedModels=document?.modelSelection?.models||[];const selectedPrompts=document?.promptSelection?.prompts||[];const strategy=document?.modelSelection?.strategy||(selectedModels.length>1?"parallel":"single");
 const perform=async(work:()=>Promise<void>)=>{setBusy(true);setError(null);try{await work()}catch(r){setError(r instanceof Error?r.message:String(r))}finally{setBusy(false)}};
 const open=(record:RecordFile<TaskDef>)=>{setSelected(record);setSource(record.document?JSON.stringify(record.document,null,2):"");setTarget(workspaceId==="shared"||record.source==="workspace"?record.path:null)};useEffect(()=>{if(snapshot&&!selected&&snapshot.tasks[0])open(snapshot.tasks[0])},[snapshot]);
 const update=(next:TaskDef)=>{if(workspaceId!=="shared"&&selected?.source==="shared"&&!target)setTarget(`tasks/${slug(next.id)}.json`);setSource(JSON.stringify(next,null,2))};
 const updateModels=(models:string[],nextStrategy:ModelStrategy=strategy)=>{if(!document)return;update({...document,modelSelection:{models,strategy:models.length<=1&&nextStrategy==="parallel"?"single":nextStrategy}})};
 const toggleModel=(id:string)=>updateModels(selectedModels.includes(id)?selectedModels.filter(x=>x!==id):[...selectedModels,id],selectedModels.length===0&&strategy==="single"?"single":strategy);
 const updatePrompts=(ids:string[])=>{if(!document)return;update({...document,promptSelection:{prompts:ids,separator:document.promptSelection?.separator??"\n\n"}})};
 const togglePrompt=(id:string)=>updatePrompts(selectedPrompts.includes(id)?selectedPrompts.filter(x=>x!==id):[...selectedPrompts,id]);
 const movePrompt=(index:number,delta:number)=>{const next=[...selectedPrompts],to=index+delta;if(to<0||to>=next.length)return;[next[index],next[to]]=[next[to],next[index]];updatePrompts(next)};
 const save=()=>perform(async()=>{if(!document)throw new Error("Task JSON is invalid");const path=target||`tasks/${slug(document.id)}.json`;await request(`/api/workspaces/${encodeURIComponent(workspaceId)}/file`,{method:"PUT",body:JSON.stringify({path,content:JSON.stringify(document,null,2)})});const next=await load();const saved=next.tasks.find(row=>row.path===path&&(workspaceId==="shared"||row.source==="workspace"))||next.tasks.find(row=>row.document?.id===document.id);if(saved)open(saved)});
 if(!snapshot)return <section className="resource-view"><div className="studio-empty">Loading task library…</div></section>;
 return <section className="resource-view task-model-editor"><div className="resource-heading"><div><span>PROCESSING RESOURCES</span><h1>Task library</h1><p>Tasks define the semantic operation. LLM tasks select model/profile configurations and the ordered reusable prompts that make up the request.</p></div></div>{error&&<div className="demo-notice"><b>Task editor error</b><span>{error}</span></div>}
 <div className="resource-table"><div className="resource-row resource-head"><span>Task</span><span>Implementation</span><span>Source</span><span>Models</span><span>Prompts</span></div>{snapshot.tasks.map(row=><button className="resource-row" key={`${row.workspaceId}:${row.path}`} onClick={()=>open(row)}><b>{row.document?.label||row.document?.id||row.path}</b><code>{row.document?.implementation||"—"}</code><span>{row.source}</span><span>{row.document?.modelSelection?.models?.length||0}</span><em>{row.document?.promptSelection?.prompts?.length||0}</em></button>)}</div>
 {selected&&<div className="task-editor-layout"><div className="task-definition-panel"><div className="llm-subhead"><div><span>TASK DEFINITION</span><b>{document?.label||document?.id||selected.path}</b></div><div className="studio-actions"><button className="primary" onClick={save} disabled={busy||!document}>Save task</button></div></div><textarea className="raw-json-editor task-raw-editor" value={source} onChange={e=>setSource(e.target.value)}/></div>
 <div className="task-model-selection"><div className="llm-subhead"><div><span>MODEL / PROFILE DISPATCH</span><b>Execution configurations allowed for this task</b></div></div><label className="strategy-field"><span>DISPATCH STRATEGY</span><select value={strategy} onChange={e=>updateModels(selectedModels,e.target.value as ModelStrategy)}><option value="single">single</option><option value="parallel">parallel</option><option value="compare">compare</option><option value="fallback">fallback</option></select></label><div className="task-model-list">{enabledModels.map(row=>{const item=row.document!,checked=selectedModels.includes(item.id);return <label className={`task-model-option ${checked?"selected":""}`} key={item.id}><input type="checkbox" checked={checked} onChange={()=>toggleModel(item.id)}/><span><b>{item.label||item.id}</b><small>{item.kind} · inherits {item.inherits} · {row.resolved?.model||item.model||"inherited model"}</small></span><em>temp {String((row.resolved?.defaults||item.defaults||{}).temperature??"—")}</em></label>})}</div>
 <div className="llm-subhead" style={{marginTop:18}}><div><span>PROMPT COMPOSITION</span><b>Ordered prompts used by this task</b></div></div><p className="task-model-help">This is the replacement for the old profile <code>prompt_text</code> list. Profiles are model settings only; prompt ordering belongs here on the Task.</p><div className="task-model-list">{prompts.map(row=>{const item=row.document!,checked=selectedPrompts.includes(item.id),index=selectedPrompts.indexOf(item.id);return <div className={`task-model-option ${checked?"selected":""}`} key={item.id}><input type="checkbox" checked={checked} onChange={()=>togglePrompt(item.id)}/><span><b>{item.label||item.id}</b><small>{item.description||row.path}</small></span>{checked&&<em><button onClick={()=>movePrompt(index,-1)} disabled={index===0}>↑</button> {index+1} <button onClick={()=>movePrompt(index,1)} disabled={index===selectedPrompts.length-1}>↓</button></em>}</div>})}</div><div className="task-model-summary"><span>Persisted LLM task policy</span><pre className="mini-code">{JSON.stringify({modelSelection:document?.modelSelection||{models:[],strategy:"single"},promptSelection:document?.promptSelection||{prompts:[],separator:"\n\n"}},null,2)}</pre></div></div></div>}
 </section>;
}
