import { useEffect, useState } from "react";

type IncludeSpec = { workspaceId: string; includeInherited: boolean };
type Workspace = { id:string; label:string; description:string; root:string; includes?:IncludeSpec[]; effectiveIncludes?:string[]; workflowFileCount:number; operationFileCount:number; datatypeFileCount?:number; representationFileCount?:number; concreteDatatypeFileCount?:number; modelFileCount?:number; promptFileCount?:number };

export function WorkspaceSettingsPanel({workspace,workspaces,fileCount,implementationCount,onSwitch,onSaved}:{workspace:Workspace;workspaces:Workspace[];fileCount:number;implementationCount:number;onSwitch:()=>void;onSaved:()=>Promise<unknown>}) {
  const [includes,setIncludes]=useState<IncludeSpec[]>(workspace.includes||[]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  useEffect(()=>setIncludes(workspace.includes||[]),[workspace.id,JSON.stringify(workspace.includes||[])]);
  const selected=(id:string)=>includes.find(item=>item.workspaceId===id);
  const toggle=(id:string)=>setIncludes(current=>selected(id)?current.filter(item=>item.workspaceId!==id):[...current,{workspaceId:id,includeInherited:true}]);
  const changeTransitive=(id:string,value:boolean)=>setIncludes(current=>current.map(item=>item.workspaceId===id?{...item,includeInherited:value}:item));
  const move=(index:number,delta:number)=>setIncludes(current=>{const target=index+delta;if(target<0||target>=current.length)return current;const next=[...current];[next[index],next[target]]=[next[target],next[index]];return next});
  const save=async()=>{setBusy(true);setMessage("");try{const response=await fetch(`/api/workspaces/${encodeURIComponent(workspace.id)}/settings`,{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({includes})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||payload.detail||response.statusText);await onSaved();setMessage("Workspace inclusion order saved to disk.")}catch(reason){setMessage(reason instanceof Error?reason.message:String(reason))}finally{setBusy(false)}};
  const choices=workspaces.filter(item=>item.id!==workspace.id);
  const byId=new Map(workspaces.map(item=>[item.id,item]));
  return <section className="resource-view workspace-settings-page"><div className="resource-heading"><div><span>WORKSPACE SETUP</span><h1>{workspace.label}</h1><p>{workspace.root}</p></div><div className="workspace-settings-actions"><button onClick={onSwitch}>Switch workspace</button><button className="primary" disabled={busy||workspace.id==="shared"} onClick={()=>void save()}>{busy?"Saving…":"Save inclusions"}</button></div></div>
    <div className="settings-grid"><label><span>WORKSPACE TYPE</span><select value={workspace.id==="shared"?"shared":"project"} disabled><option value="shared">Shared library</option><option value="project">Project workspace</option></select><small>{fileCount} editable local text files discovered from disk.</small></label><label><span>ENGINE IMPLEMENTATIONS</span><select value={implementationCount} disabled><option value={implementationCount}>{implementationCount} registered implementations</option></select></label></div>
    <div className="workspace-inclusion-editor"><div className="llm-subhead"><div><span>FILESYSTEM INCLUSIONS</span><b>Low-to-high resource precedence</b><small>Shared is selected by default but can be removed. Included workspaces override earlier layers; {workspace.label} overrides every included layer.</small></div></div>
      <div className="workspace-layer-list">{includes.map((spec,index)=>{const item=byId.get(spec.workspaceId);return <div className="workspace-layer" key={spec.workspaceId}><b>{index+1}</b><span><strong>{item?.label||spec.workspaceId}</strong><small>{item?.root||"Missing workspace"}</small></span><label><input type="checkbox" checked={spec.includeInherited} disabled={spec.workspaceId==="shared"} onChange={event=>changeTransitive(spec.workspaceId,event.target.checked)}/> {spec.workspaceId==="shared"?"No inherited layers":"Include its inherited workspaces"}</label><button disabled={index===0} onClick={()=>move(index,-1)}>↑</button><button disabled={index===includes.length-1} onClick={()=>move(index,1)}>↓</button><button onClick={()=>toggle(spec.workspaceId)}>Remove</button></div>})}<div className="workspace-layer current"><b>{includes.length+1}</b><span><strong>{workspace.label}</strong><small>Current workspace · highest precedence</small></span><em>override layer</em></div></div>
      {workspace.id!=="shared"&&<div className="workspace-include-choices"><span>AVAILABLE WORKSPACES</span>{choices.map(item=><label key={item.id}><input type="checkbox" checked={Boolean(selected(item.id))} onChange={()=>toggle(item.id)}/><b>{item.label}</b><small>{item.operationFileCount} operations · {(item.datatypeFileCount||0)+(item.representationFileCount||0)+(item.modelFileCount||0)+(item.promptFileCount||0)} catalog resources</small></label>)}</div>}{message&&<div className={`demo-notice ${message.includes("saved")?"connected":""}`}><b>{message.includes("saved")?"SAVED":"ERROR"}</b><span>{message}</span></div>}
    </div>
  </section>;
}
