import { useEffect, useState } from "react";

type Summary={workflows:number;goals:number;operations:number;datatypes:number;representations:number;models:number;files:number};
type Layer={id:string;label:string;description?:string};
type RecordFile={source?:string;workspaceId?:string};
type Counts={local:number;inherited:number};
type Breakdown=Record<"workflows"|"goals"|"operations"|"datatypes"|"models"|"files",Counts>;
const emptyBreakdown:Breakdown={workflows:{local:0,inherited:0},goals:{local:0,inherited:0},operations:{local:0,inherited:0},datatypes:{local:0,inherited:0},models:{local:0,inherited:0},files:{local:0,inherited:0}};
const split=(records:readonly RecordFile[],workspaceId:string):Counts=>records.reduce((counts,record)=>{if(record.source==="workspace"||record.workspaceId===workspaceId)counts.local+=1;else counts.inherited+=1;return counts},{local:0,inherited:0});
const request=async(path:string)=>{const response=await fetch(path);const payload=await response.json();if(!response.ok)throw new Error(payload.detail||payload.error||response.statusText);return payload};

export function WorkspaceOverview({workspaceId,label,description,summary,inheritedWorkspaces,onOpenWorkflow}:{workspaceId:string;label:string;description?:string;summary:Summary;inheritedWorkspaces:Layer[];onOpenWorkflow?:()=>void}){
 const[breakdown,setBreakdown]=useState<Breakdown>(emptyBreakdown),[contributions,setContributions]=useState<Record<string,number>>({}),[error,setError]=useState("");
 useEffect(()=>{let active=true;void(async()=>{try{const[workspaceSnapshot,goals,operations,datatypes,representations,models,...inheritedSnapshots]=await Promise.all([request(`/workbench/workspaces/${encodeURIComponent(workspaceId)}/snapshot?scope=shell`),request(`/workbench/workspaces/${encodeURIComponent(workspaceId)}/goals`),request(`/workbench/workspaces/${encodeURIComponent(workspaceId)}/operations`),request(`/workbench/workspaces/${encodeURIComponent(workspaceId)}/datatypes`),request(`/workbench/workspaces/${encodeURIComponent(workspaceId)}/representations`),request(`/workbench/workspaces/${encodeURIComponent(workspaceId)}/models`),...inheritedWorkspaces.map(layer=>request(`/workbench/workspaces/${encodeURIComponent(layer.id)}/snapshot?scope=shell`))]);const families={workflows:workspaceSnapshot.workflows||[],goals:goals.resources||[],operations:operations.operations||[],datatypes:[...(datatypes.datatypes||[]),...(representations.representations||[])],models:models.models||[]} as const;const next:Breakdown={...emptyBreakdown,workflows:split(families.workflows,workspaceId),goals:split(families.goals,workspaceId),operations:split(families.operations,workspaceId),datatypes:split(families.datatypes,workspaceId),models:split(families.models,workspaceId),files:{local:(workspaceSnapshot.files||[]).length,inherited:inheritedSnapshots.reduce((total,snapshot)=>total+(snapshot.files||[]).length,0)}};const layerCounts:Record<string,number>={};Object.values(families).flat().forEach(record=>{if(record.workspaceId&&record.workspaceId!==workspaceId)layerCounts[record.workspaceId]=(layerCounts[record.workspaceId]||0)+1});inheritedWorkspaces.forEach((layer,index)=>{layerCounts[layer.id]=(layerCounts[layer.id]||0)+(inheritedSnapshots[index]?.files||[]).length});if(active){setBreakdown(next);setContributions(layerCounts);setError("")}}catch(reason){if(active)setError(reason instanceof Error?reason.message:String(reason))}})();return()=>{active=false}},[workspaceId,JSON.stringify(inheritedWorkspaces.map(layer=>layer.id))]);
 const rows=[{key:"goals",name:"Goals",role:"workspace intent",fallback:summary.goals},{key:"operations",name:"Operations",role:"available capabilities",fallback:summary.operations},{key:"datatypes",name:"Datatypes",role:"typed contracts",fallback:summary.datatypes+summary.representations},{key:"models",name:"Models",role:"model choices",fallback:summary.models},{key:"files",name:"Workspace files",role:"persistent knowledge",fallback:summary.files}] as const;
 const workflowCounts=breakdown.workflows.local+breakdown.workflows.inherited?breakdown.workflows:{local:summary.workflows,inherited:0};
 return <section className="workspace-overview" id="overview-top"><div className="resource-heading"><div><span>HUMAN + AI BLACKBOARD</span><h1>{label}</h1><p>{description||"A filesystem workspace for defining goals, assembling Operations into workflows, and working with persistent knowledge."}</p></div>{onOpenWorkflow?<button type="button" onClick={onOpenWorkflow}>Open current workflow</button>:<button type="button" disabled>No workflow available</button>}</div><div className="checks-summary" id="overview-counts"><div className="check-score">{workflowCounts.local+workflowCounts.inherited}<small> workflows</small><span>{workflowCounts.local} local · {workflowCounts.inherited} inherited</span></div><div className="check-list workspace-count-list" role="list">{rows.map(row=>{const counts=breakdown[row.key];const total=counts.local+counts.inherited||row.fallback;return <div key={row.name} role="listitem"><span aria-hidden="true">•</span><b>{row.name}</b><small><strong>{total}</strong> total · {counts.local} local · {counts.inherited||Math.max(0,total-counts.local)} inherited</small><em>{row.role}</em></div>})}</div></div><section className="workspace-inheritance-summary" id="overview-inheritance"><div><span>INHERITED WORKSPACES</span><h2>{inheritedWorkspaces.length} effective layer{inheritedWorkspaces.length===1?"":"s"}</h2><p>Resources resolve from the lowest layer upward; {label} remains the highest-precedence local layer.</p></div><div className="workspace-inherited-layers">{inheritedWorkspaces.length?inheritedWorkspaces.map((layer,index)=><article key={layer.id}><b>{index+1}</b><span><strong>{layer.label}</strong><small>{layer.id}</small><p>{layer.description||"Inherited filesystem workspace"}</p></span><em>{contributions[layer.id]||0} visible items</em></article>):<p>No inherited workspaces. Every visible resource is local.</p>}<article className="current"><b>{inheritedWorkspaces.length+1}</b><span><strong>{label}</strong><small>{workspaceId}</small><p>Current workspace and highest-precedence override layer.</p></span><em>local</em></article></div></section>{error&&<div className="demo-notice"><b>COUNT STATUS</b><span>{error}</span></div>}</section>;
}
