(
  (kind model)
  (id https.llm.c.singularitynet.io.v1-qwen_qwen3.5-35b-a3b)
  (label qwen/qwen3.5-35b-a3b)
  (description "Discovered from SingularityNET LLM.")
  (parents ([]
    https.llm.c.singularitynet.io.v1
  ))
  (model qwen/qwen3.5-35b-a3b)
  (enabled false)
  (capabilities (
    (audio false)
    (code false)
    (functionCalling false)
    (json false)
    (jsonMode false)
    (local false)
    (multimodal false)
    (reasoning false)
    (text true)
    (tools false)
    (vision false)
  ))
  (limits (
    (contextWindow null)
    (maxOutputTokens null)
  ))
  (pricing ())
  (properties (
    (id qwen/qwen3.5-35b-a3b)
    (owned_by snet+cudo)
    (object model)
    (created 0)
    (ownedBy snet+cudo)
  ))
  (providerMetadata (
    (id qwen/qwen3.5-35b-a3b)
    (owned_by snet+cudo)
    (object model)
    (created 0)
  ))
  (discovery (
    (managed true)
    (backendId https.llm.c.singularitynet.io.v1)
    (remoteModelId qwen/qwen3.5-35b-a3b)
  ))
  (categories ([]
    filtered/vision
  ))
)
