(
  (kind semantic_datatype)
  (id entity_collection)
  (label "Entity Collection")
  (description "A collection of semantic entities independent of the representation used to encode them.")
  (implements (
    (information ())
  ))
  (implementedBy (
    (object_properties ())
    (prolog_fact_set ())
    (symbolic_fact_set ())
  ))
  (inheritedBy (
    (object_properties (
      (lend ([]
        *
      ))
      (withhold ([]
        id
        label
        description
        implements
        implementedBy
        preferredImplementation
      ))
    ))
    (prolog_fact_set (
      (lend ([]
        *
      ))
      (withhold ([]
        id
        label
        description
        implements
        implementedBy
        preferredImplementation
      ))
    ))
    (symbolic_fact_set (
      (lend ([]
        *
      ))
      (withhold ([]
        id
        label
        description
        implements
        implementedBy
        preferredImplementation
      ))
    ))
  ))
  (inheritsFrom (
    (information (
      (borrow ([]
        *
      ))
      (exclude ([]))
    ))
  ))
)
