(
  (kind semantic_datatype)
  (id entity)
  (label Entity)
  (description "A stable thing or candidate object represented independently of any concrete encoding.")
  (implements (
    (information ())
  ))
  (implementedBy (
    (image_region ())
    (object_properties ())
  ))
  (inheritedBy (
    (image_region (
      (lend ([]
        *
      ))
      (withhold ([]
        id
        label
        description
        implements
        implementedBy
        preferredImplementation
      ))
    ))
    (object_properties (
      (lend ([]
        *
      ))
      (withhold ([]
        id
        label
        description
        implements
        implementedBy
        preferredImplementation
      ))
    ))
  ))
  (inheritsFrom (
    (information (
      (borrow ([]
        *
      ))
      (exclude ([]))
    ))
  ))
)
