(
  (kind semantic_datatype)
  (id entity)
  (label Entity)
  (description "A stable thing or candidate object represented independently of any concrete encoding.")
  (specializations (
    (image_region (
      (lend ([]
        *
      ))
      (withhold ([]
        id
        label
        description
        implements
        specializations
        preferredSpecialization
      ))
    ))
    (object_properties (
      (lend ([]
        *
      ))
      (withhold ([]
        id
        label
        description
        implements
        specializations
        preferredSpecialization
      ))
    ))
  ))
  (implements (
    (information (
      (borrow ([]
        *
      ))
      (exclude ([]))
    ))
  ))
)
