(
  (kind semantic_datatype)
  (id program)
  (label Program)
  (description "Executable or interpretable instructions independent of their source language and storage representation.")
  (specializations (
    (prolog_program (
      (lend ([]
        *
      ))
      (withhold ([]
        id
        label
        description
        implements
        specializations
        preferredSpecialization
      ))
    ))
    (turtle_program_set (
      (lend ([]
        *
      ))
      (withhold ([]
        id
        label
        description
        implements
        specializations
        preferredSpecialization
      ))
    ))
  ))
  (implements (
    (information (
      (borrow ([]
        *
      ))
      (exclude ([]))
    ))
  ))
)
