(
  (kind semantic_datatype)
  (id world_state)
  (label "World State")
  (description "The semantic state of a world at a point in time.")
  (implements (
    (information ())
  ))
  (implementedBy (
    (object_properties ())
    (prolog_fact_set ())
    (symbolic_fact_set ())
  ))
  (inheritedBy (
    (object_properties (
      (lend ([]
        *
      ))
      (withhold ([]
        id
        label
        description
        implements
        implementedBy
        preferredImplementation
      ))
    ))
    (prolog_fact_set (
      (lend ([]
        *
      ))
      (withhold ([]
        id
        label
        description
        implements
        implementedBy
        preferredImplementation
      ))
    ))
    (symbolic_fact_set (
      (lend ([]
        *
      ))
      (withhold ([]
        id
        label
        description
        implements
        implementedBy
        preferredImplementation
      ))
    ))
  ))
  (inheritsFrom (
    (information (
      (borrow ([]
        *
      ))
      (exclude ([]))
    ))
  ))
)
