"""Shared object-memory contracts for PROLOG, GPT, and PYTHON backends.

The package supplements the existing ARC3 debugger. It does not replace
Arc3Runner, ActionTreeStore, GptArcAnalyzer, SWIPrologBridge, or the generated
Prolog artifact contracts.
"""

from .adapters.adapters import (
    GridAdapter,
    GridPerceptionBatch,
    ImageAdapter,
    LearnedPartRoleProvider,
    MediaPerceptionBatch,
    PerceptionAdapter,
    SimpleVideoAdapter,
    normalize_grid_structure,
    normalize_image_structure,
)
from .evaluation.acceptance import AcceptanceReport, build_acceptance_report, write_acceptance_report
from .runtime.capture import SemanticGridCaptureObserver, standard_semantic_grid_observer
from .runtime.catalog import IdentityCatalogEntry, SemanticIdentityCatalog
from .evaluation.calibration import (
    CalibrationPoint,
    RecognitionCalibrationReport,
    RecognitionCalibrationPolicy,
    RecognitionCalibrator,
    ReliabilityBin,
)
from .evaluation.benchmark import (
    PerceptionBenchmarkResult,
    PerceptionBenchmarkRunner,
    PerceptionFixture,
    ProviderAblationRunner,
    RasterPerturbationGenerator,
)
from .forms.forms import AbstractGenerativeForm, FitResult, GenerativeForm
from .environments.environment_fixtures import (
    EnvironmentProgressionFixtures,
    environment_progression_fixtures,
    fixed_camera_physics_fixtures,
    rendered_arcade_fixtures,
    top_down_manipulation_fixtures,
)
from .runtime.integration import (
    GAME_OBJECT_LEARNER_SCHEMA_VERSION,
    GameObjectLearnerPayload,
    GameObjectLearnerPlugin,
    GameObjectLearnerResult,
    GameObjectLearnerSchema,
    IntegrationError,
    IntegrationValidator,
    Phase2LearnerPayloadBuilder,
    PipelineGameObjectLearnerPlugin,
    phase2_transformation_learner,
    phase2_transition_analyzer,
    phase2_rule_inducer,
    phase2_rule_executor,
    phase2_rule_ranker,
)
from .core.learning import (
    GameLearningPipeline,
    LearningStepResult,
    OutcomeChannel,
    PredictionEvaluator,
    PredictionGrade,
    PredictionGradeStatus,
    RuleEvidence,
    RuleExecutor,
    RuleInducer,
    RuleRanker,
    RuleRivalSet,
    TransformationCandidate,
    TransformationLearner,
    TransitionAnalyzer,
    TransitionRecord,
)
from .core.models import (
    ActionRecommendation,
    ArtifactRef,
    CandidateObject,
    CommittedAtom,
    ConfidenceHistoryRecord,
    EncounterRecord,
    EvidencePolarity,
    EvidenceRecord,
    ExecutionMode,
    IdentityDecision,
    IdentityMemoryCheckpoint,
    InstanceParameters,
    MatchProposal,
    MergeDecision,
    NormalizedResult,
    Observation,
    ObjectChange,
    PHASE2_SCHEMA_VERSION,
    PredictionRecord,
    PredictionGradeRecord,
    ProvenanceRef,
    RecognitionAccount,
    ResidualCandidate,
    ResidualDisposition,
    SplitDecision,
    TransitionRule,
    TurtleProgramRef,
    deterministic_identifier,
)
from .core.memory import EncounterLog, ResidualGate, SingleWriter, SymbolicMemory
from .core.prediction import PredictionLedger, RuleStore
from .adapters.providers import (
    ArtifactProvider,
    GptArtifactProvider,
    PrologProvider,
    ProviderCapabilities,
    PythonProvider,
    UnsupportedProviderCapability,
)
from .core.recognition import (
    ChangeDetector,
    CorrespondenceEvidenceBuilder,
    EncounterChangeSession,
    InstanceMatcher,
    PartialVisibilityCompletion,
    RecognitionSession,
    RegistryCorrespondenceAuthority,
    StructuralCorrespondenceInferer,
    ResidualAnalyzer,
    TurtleReconstructionEvidenceBuilder,
)
from .evaluation.recognition_benchmark import (
    RecognitionBenchmarkResult,
    RecognitionBenchmarkRunner,
    RecognitionFixture,
)
from .runtime.replay import (
    ActionTreeSemanticReplay,
    AtomSpaceSemanticBackend,
    AtomSpaceTransport,
    MettaFileAtomSpaceTransport,
    PrologSemanticBackend,
    SemanticRecordCodec,
)
from .adapters.sprite import AlphaContourProvider, SpriteAdapter
from .runtime.transcript import TranscriptComparison, TranscriptScorer
from .core.store import ArtifactIndex, InMemorySemanticBackend, SemanticStoreBackend, SymbolicStore

__all__ = [
    "ArtifactProvider",
    "AtomSpaceSemanticBackend",
    "AtomSpaceTransport",
    "ActionRecommendation",
    "AcceptanceReport",
    "AlphaContourProvider",
    "ActionTreeSemanticReplay",
    "ArtifactRef",
    "ArtifactIndex",
    "CandidateObject",
    "CalibrationPoint",
    "ChangeDetector",
    "AbstractGenerativeForm",
    "CommittedAtom",
    "ConfidenceHistoryRecord",
    "CorrespondenceEvidenceBuilder",
    "EncounterRecord",
    "EnvironmentProgressionFixtures",
    "EncounterLog",
    "EncounterChangeSession",
    "EvidencePolarity",
    "EvidenceRecord",
    "ExecutionMode",
    "FitResult",
    "GameLearningPipeline",
    "GAME_OBJECT_LEARNER_SCHEMA_VERSION",
    "GameObjectLearnerPayload",
    "GameObjectLearnerPlugin",
    "GameObjectLearnerResult",
    "GameObjectLearnerSchema",
    "GenerativeForm",
    "GptArtifactProvider",
    "GridAdapter",
    "ImageAdapter",
    "LearnedPartRoleProvider",
    "MediaPerceptionBatch",
    "GridPerceptionBatch",
    "IntegrationError",
    "IntegrationValidator",
    "IdentityDecision",
    "IdentityMemoryCheckpoint",
    "IdentityCatalogEntry",
    "InstanceParameters",
    "InstanceMatcher",
    "InMemorySemanticBackend",
    "LearningStepResult",
    "MatchProposal",
    "MettaFileAtomSpaceTransport",
    "MergeDecision",
    "NormalizedResult",
    "Observation",
    "ObjectChange",
    "OutcomeChannel",
    "PerceptionAdapter",
    "PerceptionBenchmarkResult",
    "PerceptionBenchmarkRunner",
    "PerceptionFixture",
    "ProviderAblationRunner",
    "SimpleVideoAdapter",
    "PartialVisibilityCompletion",
    "Phase2LearnerPayloadBuilder",
    "phase2_transformation_learner",
    "phase2_transition_analyzer",
    "normalize_grid_structure",
    "normalize_image_structure",
    "phase2_rule_inducer",
    "phase2_rule_executor",
    "phase2_rule_ranker",
    "PipelineGameObjectLearnerPlugin",
    "PredictionEvaluator",
    "PredictionGrade",
    "PredictionGradeStatus",
    "PredictionLedger",
    "PredictionRecord",
    "PredictionGradeRecord",
    "PHASE2_SCHEMA_VERSION",
    "ProvenanceRef",
    "PrologProvider",
    "ProviderCapabilities",
    "PrologSemanticBackend",
    "PythonProvider",
    "ResidualCandidate",
    "ResidualAnalyzer",
    "ResidualDisposition",
    "ResidualGate",
    "ReliabilityBin",
    "RecognitionAccount",
    "RecognitionCalibrationReport",
    "RecognitionCalibrationPolicy",
    "RecognitionCalibrator",
    "RecognitionBenchmarkResult",
    "RecognitionBenchmarkRunner",
    "RecognitionFixture",
    "RecognitionSession",
    "RasterPerturbationGenerator",
    "RegistryCorrespondenceAuthority",
    "RuleEvidence",
    "RuleExecutor",
    "RuleInducer",
    "RuleRanker",
    "RuleRivalSet",
    "RuleStore",
    "SingleWriter",
    "SpriteAdapter",
    "SemanticStoreBackend",
    "SemanticRecordCodec",
    "SemanticGridCaptureObserver",
    "SemanticIdentityCatalog",
    "standard_semantic_grid_observer",
    "SplitDecision",
    "SymbolicMemory",
    "StructuralCorrespondenceInferer",
    "SymbolicStore",
    "TransformationCandidate",
    "TransformationLearner",
    "TransitionAnalyzer",
    "TransitionRecord",
    "TransitionRule",
    "TranscriptComparison",
    "TranscriptScorer",
    "UnsupportedProviderCapability",
    "TurtleProgramRef",
    "TurtleReconstructionEvidenceBuilder",
    "deterministic_identifier",
    "build_acceptance_report",
    "environment_progression_fixtures",
    "fixed_camera_physics_fixtures",
    "rendered_arcade_fixtures",
    "top_down_manipulation_fixtures",
    "write_acceptance_report",
]
