object_correspondence(yellow_playfield,yellow_playfield,1.0,[color,bbox,cell_runs,area,role],[]).
object_correspondence(left_gray_border,left_gray_border,1.0,[color,bbox,size,area,shape],[]).
object_correspondence(green_maze_structure,green_maze_structure,0.945,[color,bbox,area,connectivity,contained_objects],[cell_runs]).
object_correspondence(green_upper_chamber_frame,green_upper_chamber_frame,1.0,[color,bbox,size,area,shape,symmetry],[]).
object_correspondence(gray_upper_chamber_interior,gray_upper_chamber_interior,1.0,[color,bbox,cell_runs,area,shape],[]).
object_correspondence(upper_red_hook_glyph,upper_red_hook_glyph,1.0,[color,bbox,occupied_geometry,shape],[]).
object_correspondence(upper_red_square,upper_red_square,1.0,[color,bbox,occupied_cells,shape],[]).
object_correspondence(green_chamber_stem,green_chamber_stem,1.0,[color,bbox,size,area,orientation],[]).
object_correspondence(green_main_platform,green_main_platform,0.941,[color,bbox,area,contained_objects],[cell_runs]).
object_correspondence(yellow_inner_cavity,yellow_inner_cavity,1.0,[color,bbox,size,area,cell_runs,shape],[]).
object_correspondence(blue_black_player,blue_black_player,1.0,[colors,bbox,size,occupied_cells,shape],[]).
object_correspondence(black_player_head,black_player_head,1.0,[color,bbox,occupied_cells,shape],[]).
object_correspondence(blue_player_tail,blue_player_tail,1.0,[color,bbox,occupied_cells,shape],[]).
object_correspondence(bottom_center_gate,bottom_center_gate,0.98,[colors,size,area,shape,subcomponents],[bbox,position]).
object_correspondence(gray_gate_cap,gray_gate_cap,0.98,[color,size,area,shape,orientation],[bbox,position]).
object_correspondence(red_gate_base,red_gate_base,0.98,[color,size,area,shape,orientation],[bbox,position]).
object_correspondence(lower_left_control_panel,lower_left_control_panel,1.0,[colors,bbox,size,area,shape,contained_objects],[]).
object_correspondence(lower_left_red_hook_glyph,lower_left_red_hook_glyph,1.0,[color,bbox,size,area,cell_runs,shape],[]).
object_correspondence(lower_left_red_square,lower_left_red_square,1.0,[color,bbox,size,area,cell_runs,shape],[]).
object_correspondence(bottom_status_panel,bottom_status_panel,0.99,[bbox,size,area,shape,orientation,cyan_indicators],[colors,internal_bar_partition]).
object_correspondence(bottom_dark_status_bar,bottom_dark_status_bar,0.976,[color,height,orientation,right_edge],[bbox,width,area,left_edge]).
object_correspondence(left_cyan_status_cell,left_cyan_status_cell,1.0,[color,bbox,size,area,shape],[]).
object_correspondence(middle_cyan_status_cell,middle_cyan_status_cell,1.0,[color,bbox,size,area,shape],[]).
object_correspondence(right_cyan_status_cell,right_cyan_status_cell,1.0,[color,bbox,size,area,shape],[]).

correspondence_evidence(bottom_center_gate,translation,delta(-5,0)).
correspondence_evidence(bottom_center_gate,parent_cells,[rows(45,49,34,38)]).
correspondence_evidence(bottom_center_gate,current_cells,[rows(45,49,29,33)]).
correspondence_evidence(green_main_platform,changed_green_cells,[removed(rows(45,49,29,33)),added(rows(45,49,34,38))]).
correspondence_evidence(bottom_dark_status_bar,current_is_parent_subset,[rows(61,62,14,54)]).
